package plan_estudios.view;

import docentes.controller.DocenteController;
import docentes.dao.DocenteDAOImpl;
import docentes.model.Docente;
import java.util.ArrayList;
import java.util.List;
import main.VentanaPrincipal;
import plan_estudios.controller.CursoController;
import plan_estudios.controller.GradoController;
import plan_estudios.model.Curso;
import plan_estudios.model.Grado;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Alexis
 */
public class DialogNuevoCurso extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogNuevoCurso.class.getName());
    private final CursoController cursoController;
    private final PanelPlanEstudios panelPadre;
    private final List<Grado> gradosMapeados;
    private final List<Docente> docentesMapeados;
    private final Curso cursoEdicion;
    
    /**
     * Creates new form DialogNuevoCurso
     * @param parent
     * @param modal
     */
    public DialogNuevoCurso(java.awt.Frame parent, boolean modal, CursoController cursoController, PanelPlanEstudios panelPadre, Curso cursoAEditar, List<Grado> grados, List<Docente> docentes) {
        super(parent, modal);
        this.cursoController = cursoController;
        this.panelPadre = panelPadre;
        this.cursoEdicion = cursoAEditar; 
        this.gradosMapeados = (grados != null) ? grados : new ArrayList<>();
        this.docentesMapeados = (docentes != null) ? docentes : new ArrayList<>();
        
        initComponents();
        this.setLocationRelativeTo(parent);

        inicializarCombos();

        if (cursoAEditar != null) {
            nombrePanel.setText("Modificar Datos del Curso: " + cursoAEditar.getCodigo());
            btnGuardar.setText("Actualizar");

            txtNombreCurso.setText(cursoAEditar.getNombre());
            spinNumeroHoras.setValue(cursoAEditar.getHorasSemanales());

            if (cursoAEditar.getGradoAsignado() != null) {
                cboGrado.setSelectedItem(cursoAEditar.getGradoAsignado().getNombre() + " - " + cursoAEditar.getGradoAsignado().getNivel());
            }

            if (cursoAEditar.getDocente() != null) {
                cboDocentes.setSelectedItem(cursoAEditar.getDocente().getApellidos() + ", " + cursoAEditar.getDocente().getNombres());
            }
        }
    }

    private void inicializarCombos() {

        for (Grado g : gradosMapeados) {
            cboGrado.addItem(g.getNombre() + " - " + g.getNivel());
        }

        for (Docente d : docentesMapeados) {
            cboDocentes.addItem(d.getApellidos() + ", " + d.getNombres());
        }
    }
    
    private Grado obtenerGradoSeleccionado() {
        int index = cboGrado.getSelectedIndex();
        if (index <= 0) {
            throw new IllegalStateException("Debe seleccionar un grado válido.");
        }
        return gradosMapeados.get(index - 1);
    }

    private Docente obtenerDocenteSeleccionado() {
        int index = cboDocentes.getSelectedIndex();
        if (index <= 0) {
            throw new IllegalStateException("Debe seleccionar un docente para el curso.");
        }
        return docentesMapeados.get(index - 1);
    }

    private Curso obtenerCursoDesdeFormulario() {
        Curso nuevoCurso = new Curso();
        nuevoCurso.setNombre(txtNombreCurso.getText());
        nuevoCurso.setHorasSemanales((int) spinNumeroHoras.getValue());
        nuevoCurso.asociarGrado(obtenerGradoSeleccionado());
        nuevoCurso.setDocente(obtenerDocenteSeleccionado());
        return nuevoCurso;
    }

    private Curso actualizarCursoDesdeFormulario() {
        Curso modificado = new Curso();
        modificado.setId(cursoEdicion.getId());
        modificado.setCodigo(cursoEdicion.getCodigo());
        modificado.setActivo(cursoEdicion.isActivo());
        
        modificado.setNombre(txtNombreCurso.getText());
        modificado.setHorasSemanales((int) spinNumeroHoras.getValue());
        modificado.asociarGrado(obtenerGradoSeleccionado());
        modificado.setDocente(obtenerDocenteSeleccionado());
        
        return modificado;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        nombrePanel = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        panelDatosCurso = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        panelRowNombre = new javax.swing.JPanel();
        lblNombreCurso = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtNombreCurso = new javax.swing.JTextField();
        panelRowGrado = new javax.swing.JPanel();
        lblFechaNacimientoAlumno = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        cboGrado = new javax.swing.JComboBox<>();
        panelRowhoras = new javax.swing.JPanel();
        lblApellidosAlumno = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        spinNumeroHoras = new javax.swing.JSpinner();
        panelRowDocente = new javax.swing.JPanel();
        lblDocenteAsignado = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        cboDocentes = new javax.swing.JComboBox<>();
        panelInferior = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 350));
        setModal(true);
        setResizable(false);

        panelPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelPrincipal.setMinimumSize(new java.awt.Dimension(495, 200));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(495, 300));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setLayout(new javax.swing.BoxLayout(panelSuperior, javax.swing.BoxLayout.X_AXIS));

        nombrePanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombrePanel.setText("Registrar Nuevo Curso");
        nombrePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        nombrePanel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        nombrePanel.setMaximumSize(new java.awt.Dimension(250, 30));
        nombrePanel.setMinimumSize(new java.awt.Dimension(250, 30));
        nombrePanel.setPreferredSize(new java.awt.Dimension(250, 30));
        panelSuperior.add(nombrePanel);

        panelPrincipal.add(panelSuperior, java.awt.BorderLayout.NORTH);

        panelCentral.setLayout(new java.awt.BorderLayout());

        panelDatosCurso.setLayout(new javax.swing.BoxLayout(panelDatosCurso, javax.swing.BoxLayout.Y_AXIS));
        panelDatosCurso.add(filler1);

        panelRowNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowNombre.setMaximumSize(new java.awt.Dimension(32767, 45));
        panelRowNombre.setOpaque(false);
        panelRowNombre.setLayout(new javax.swing.BoxLayout(panelRowNombre, javax.swing.BoxLayout.X_AXIS));

        lblNombreCurso.setText("Nombre del Curso");
        lblNombreCurso.setMaximumSize(new java.awt.Dimension(150, 30));
        lblNombreCurso.setMinimumSize(new java.awt.Dimension(150, 30));
        lblNombreCurso.setPreferredSize(new java.awt.Dimension(150, 30));
        panelRowNombre.add(lblNombreCurso);
        panelRowNombre.add(filler3);

        txtNombreCurso.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtNombreCurso.setMinimumSize(new java.awt.Dimension(250, 35));
        txtNombreCurso.setPreferredSize(new java.awt.Dimension(250, 35));
        txtNombreCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCursoActionPerformed(evt);
            }
        });
        panelRowNombre.add(txtNombreCurso);

        panelDatosCurso.add(panelRowNombre);

        panelRowGrado.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowGrado.setOpaque(false);
        panelRowGrado.setLayout(new javax.swing.BoxLayout(panelRowGrado, javax.swing.BoxLayout.X_AXIS));

        lblFechaNacimientoAlumno.setText("Grado del Curso");
        lblFechaNacimientoAlumno.setMaximumSize(new java.awt.Dimension(150, 30));
        lblFechaNacimientoAlumno.setMinimumSize(new java.awt.Dimension(150, 30));
        lblFechaNacimientoAlumno.setPreferredSize(new java.awt.Dimension(150, 30));
        panelRowGrado.add(lblFechaNacimientoAlumno);
        panelRowGrado.add(filler6);

        cboGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione un Grado --" }));
        cboGrado.setMaximumSize(new java.awt.Dimension(32767, 35));
        cboGrado.setMinimumSize(new java.awt.Dimension(250, 35));
        cboGrado.setPreferredSize(new java.awt.Dimension(250, 35));
        cboGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGradoActionPerformed(evt);
            }
        });
        panelRowGrado.add(cboGrado);

        panelDatosCurso.add(panelRowGrado);

        panelRowhoras.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowhoras.setMaximumSize(new java.awt.Dimension(32972, 45));
        panelRowhoras.setOpaque(false);
        panelRowhoras.setLayout(new javax.swing.BoxLayout(panelRowhoras, javax.swing.BoxLayout.X_AXIS));

        lblApellidosAlumno.setText("Horas Semanales");
        lblApellidosAlumno.setMaximumSize(new java.awt.Dimension(150, 35));
        lblApellidosAlumno.setMinimumSize(new java.awt.Dimension(150, 35));
        lblApellidosAlumno.setPreferredSize(new java.awt.Dimension(150, 35));
        panelRowhoras.add(lblApellidosAlumno);
        panelRowhoras.add(filler5);

        spinNumeroHoras.setModel(new javax.swing.SpinnerNumberModel(2, 1, 10, 1));
        spinNumeroHoras.setMaximumSize(new java.awt.Dimension(32767, 35));
        spinNumeroHoras.setMinimumSize(new java.awt.Dimension(64, 35));
        spinNumeroHoras.setPreferredSize(new java.awt.Dimension(64, 35));
        panelRowhoras.add(spinNumeroHoras);

        panelDatosCurso.add(panelRowhoras);

        panelRowDocente.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowDocente.setOpaque(false);
        panelRowDocente.setLayout(new javax.swing.BoxLayout(panelRowDocente, javax.swing.BoxLayout.X_AXIS));

        lblDocenteAsignado.setText("Docente del Curso");
        lblDocenteAsignado.setMaximumSize(new java.awt.Dimension(150, 35));
        lblDocenteAsignado.setMinimumSize(new java.awt.Dimension(150, 35));
        lblDocenteAsignado.setPreferredSize(new java.awt.Dimension(150, 35));
        panelRowDocente.add(lblDocenteAsignado);
        panelRowDocente.add(filler8);

        cboDocentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione un Docente --" }));
        cboDocentes.setMaximumSize(new java.awt.Dimension(32767, 35));
        cboDocentes.setMinimumSize(new java.awt.Dimension(250, 35));
        cboDocentes.setPreferredSize(new java.awt.Dimension(250, 35));
        cboDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDocentesActionPerformed(evt);
            }
        });
        panelRowDocente.add(cboDocentes);

        panelDatosCurso.add(panelRowDocente);

        panelCentral.add(panelDatosCurso, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

        panelInferior.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelInferior.setLayout(new javax.swing.BoxLayout(panelInferior, javax.swing.BoxLayout.X_AXIS));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(100, 35));
        btnCancelar.setMinimumSize(new java.awt.Dimension(100, 35));
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 35));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelInferior.add(btnCancelar);
        panelInferior.add(filler7);

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(100, 35));
        btnGuardar.setMinimumSize(new java.awt.Dimension(100, 35));
        btnGuardar.setPreferredSize(new java.awt.Dimension(100, 35));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelInferior.add(btnGuardar);

        panelPrincipal.add(panelInferior, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombreCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCursoActionPerformed

    private void cboGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGradoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (cursoController == null) return;

        try {
            final boolean exito = (cursoEdicion != null)
                ? cursoController.actualizarCurso(actualizarCursoDesdeFormulario())
                : cursoController.registrarCurso(obtenerCursoDesdeFormulario());

            if (exito) {
                mostrarMensaje("¡Operación realizada con éxito!", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                if (panelPadre != null) {
                    panelPadre.refrescarTabla(cursoController.obtenerCursos());
                }
                this.dispose();
            } else {
                mostrarMensaje("Error de persistencia en la base de datos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (IllegalArgumentException | IllegalStateException e) {
            mostrarMensaje(e.getMessage(), "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (RuntimeException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error crítico de sistema al guardar", e);
            mostrarMensaje("Ocurrió un error inesperado de sistema.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cboDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDocentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDocentesActionPerformed

    public void mostrarMensaje(String mensaje, String titulo, int tipo) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, titulo, tipo);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "No se pudo aplicar el tema nativo del sistema", ex);
        }

        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboDocentes;
    private javax.swing.JComboBox<String> cboGrado;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JLabel lblApellidosAlumno;
    private javax.swing.JLabel lblDocenteAsignado;
    private javax.swing.JLabel lblFechaNacimientoAlumno;
    private javax.swing.JLabel lblNombreCurso;
    private javax.swing.JLabel nombrePanel;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelDatosCurso;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRowDocente;
    private javax.swing.JPanel panelRowGrado;
    private javax.swing.JPanel panelRowNombre;
    private javax.swing.JPanel panelRowhoras;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JSpinner spinNumeroHoras;
    private javax.swing.JTextField txtNombreCurso;
    // End of variables declaration//GEN-END:variables
}
