
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package plan_estudios.view;
import docentes.model.Docente;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import plan_estudios.controller.CursoController;
import plan_estudios.model.Curso;
import plan_estudios.model.Grado;

/**
 *
 * @author Alexis
 */
public class PanelPlanEstudios extends javax.swing.JPanel {

    private final CursoController cursoController;
    private List<Curso> cursosCargados = new ArrayList<>();
    
    /**
     * Creates new form PanelAlumnos
     */
    public PanelPlanEstudios() {
        this.cursoController = null; 
        initComponents();
        this.setBackground(java.awt.Color.WHITE);
    }
     
    public PanelPlanEstudios(CursoController cursoController) {
        this.cursoController = cursoController;
        initComponents();
        
        this.setBackground(java.awt.Color.WHITE);
        
        tablaPlanEstudios.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        
        if (cursoController != null) {
            javax.swing.SwingUtilities.invokeLater(() -> refrescarTabla(cursoController.obtenerCursos()));
        }
    }

    public void refrescarTabla(List<Curso> cursos) {
        this.cursosCargados = (cursos != null) ? cursos : Collections.emptyList(); 
        DefaultTableModel modelo = (DefaultTableModel) tablaPlanEstudios.getModel();
        modelo.setRowCount(0); 

        for (Curso c : this.cursosCargados) {
            modelo.addRow(new Object[]{
                c.getCodigo(),
                c.getNombre(),
                c.getGradoAsignado() != null ? c.getGradoAsignado().getNombre() + " - " + c.getGradoAsignado().getNivel() : "No asignado",
                c.getHorasSemanales(),
                c.getDocente() != null ? c.getDocente().getApellidos() + ", " + c.getDocente().getNombres() : "Por asignar",
                c.isActivo() ? "ACTIVO" : "INACTIVO"
            });
        }
    }

    private void abrirDialogoEdicion(Curso cursoOriginal) {
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof java.awt.Frame frame && cursoController != null) {
            
            Curso copiaCurso = new Curso();
            copiaCurso.setId(cursoOriginal.getId());
            copiaCurso.setCodigo(cursoOriginal.getCodigo());
            copiaCurso.setNombre(cursoOriginal.getNombre());
            copiaCurso.setHorasSemanales(cursoOriginal.getHorasSemanales());
            copiaCurso.setActivo(cursoOriginal.isActivo()); 
            
            if (cursoOriginal.getDocente() != null) {
                copiaCurso.setDocente(cursoOriginal.getDocente());
            }
            if (cursoOriginal.getGradoAsignado() != null) {
                copiaCurso.asociarGrado(cursoOriginal.getGradoAsignado());
            }
            
            plan_estudios.controller.GradoController gradoController = new plan_estudios.controller.GradoController();
            docentes.controller.DocenteController docenteController = new docentes.controller.DocenteController();
            
            List<Grado> grados = gradoController.obtenerGradosActivos();
            List<Docente> docentes = docenteController.obtenerDocentes();
            
            DialogNuevoCurso dialog = new DialogNuevoCurso(frame, true, cursoController, this, copiaCurso, grados, docentes);
            dialog.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelNombre = new javax.swing.JPanel();
        nombrePanel = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 32767));
        panelAgregar = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnDarBaja = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnNuevoCurso = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        panelBusqueda = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnBuscar = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        panelCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPlanEstudios = new javax.swing.JTable();
        panelInferior = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout());

        panelPrincipal.setOpaque(false);
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setOpaque(false);
        panelSuperior.setLayout(new javax.swing.BoxLayout(panelSuperior, javax.swing.BoxLayout.Y_AXIS));

        panelNombre.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelNombre.setMinimumSize(new java.awt.Dimension(400, 30));
        panelNombre.setOpaque(false);
        panelNombre.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelNombre.setLayout(new java.awt.BorderLayout());

        nombrePanel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nombrePanel.setText("Plan de Estudios");
        nombrePanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNombre.add(nombrePanel, java.awt.BorderLayout.WEST);

        panelSuperior.add(panelNombre);
        panelSuperior.add(filler4);

        panelAgregar.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelAgregar.setMinimumSize(new java.awt.Dimension(400, 35));
        panelAgregar.setOpaque(false);
        panelAgregar.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelAgregar.setLayout(new javax.swing.BoxLayout(panelAgregar, javax.swing.BoxLayout.X_AXIS));
        panelAgregar.add(filler5);

        btnDarBaja.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDarBaja.setText("Dar de Baja Curso");
        btnDarBaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDarBaja.setMaximumSize(new java.awt.Dimension(150, 35));
        btnDarBaja.setMinimumSize(new java.awt.Dimension(150, 35));
        btnDarBaja.setPreferredSize(new java.awt.Dimension(150, 35));
        btnDarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarBajaActionPerformed(evt);
            }
        });
        panelAgregar.add(btnDarBaja);
        panelAgregar.add(filler7);

        btnNuevoCurso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNuevoCurso.setText("Nuevo Curso");
        btnNuevoCurso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoCurso.setMaximumSize(new java.awt.Dimension(140, 35));
        btnNuevoCurso.setMinimumSize(new java.awt.Dimension(140, 35));
        btnNuevoCurso.setPreferredSize(new java.awt.Dimension(140, 35));
        btnNuevoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCursoActionPerformed(evt);
            }
        });
        panelAgregar.add(btnNuevoCurso);

        panelSuperior.add(panelAgregar);
        panelSuperior.add(filler3);

        panelBusqueda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelBusqueda.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelBusqueda.setMinimumSize(new java.awt.Dimension(400, 35));
        panelBusqueda.setOpaque(false);
        panelBusqueda.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelBusqueda.setLayout(new javax.swing.BoxLayout(panelBusqueda, javax.swing.BoxLayout.X_AXIS));

        txtBuscar.setText("Buscar por Código");
        txtBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        txtBuscar.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtBuscar.setMinimumSize(new java.awt.Dimension(250, 35));
        txtBuscar.setName(""); // NOI18N
        txtBuscar.setPreferredSize(new java.awt.Dimension(250, 35));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        panelBusqueda.add(txtBuscar);
        txtBuscar.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)),
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
    panelBusqueda.add(filler1);

    btnBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    btnBuscar.setText("Buscar");
    btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnBuscar.setMaximumSize(new java.awt.Dimension(140, 35));
    btnBuscar.setMinimumSize(new java.awt.Dimension(140, 35));
    btnBuscar.setPreferredSize(new java.awt.Dimension(140, 35));
    btnBuscar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBuscarActionPerformed(evt);
        }
    });
    panelBusqueda.add(btnBuscar);

    panelSuperior.add(panelBusqueda);
    panelSuperior.add(filler2);

    panelPrincipal.add(panelSuperior, java.awt.BorderLayout.NORTH);

    panelCentral.setLayout(new java.awt.GridBagLayout());

    tablaPlanEstudios.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null}
        },
        new String [] {
            "Codigo", "Nombre", "Grado", "Horas Semanales", "Docente Asignado", "Estado del Curso"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    tablaPlanEstudios.setFillsViewportHeight(true);
    tablaPlanEstudios.setOpaque(false);
    tablaPlanEstudios.setRowHeight(40);
    tablaPlanEstudios.setShowGrid(false);
    tablaPlanEstudios.setShowHorizontalLines(true);
    tablaPlanEstudios.getTableHeader().setReorderingAllowed(false);
    tablaPlanEstudios.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tablaPlanEstudiosMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(tablaPlanEstudios);
    if (tablaPlanEstudios.getColumnModel().getColumnCount() > 0) {
        tablaPlanEstudios.getColumnModel().getColumn(0).setResizable(false);
        tablaPlanEstudios.getColumnModel().getColumn(1).setResizable(false);
        tablaPlanEstudios.getColumnModel().getColumn(2).setResizable(false);
        tablaPlanEstudios.getColumnModel().getColumn(3).setResizable(false);
        tablaPlanEstudios.getColumnModel().getColumn(4).setResizable(false);
        tablaPlanEstudios.getColumnModel().getColumn(5).setResizable(false);
    }
    javax.swing.table.JTableHeader header = tablaPlanEstudios.getTableHeader();
    header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    header.setBackground(new java.awt.Color(245, 245, 245)); // Gris muy claro
    header.setOpaque(true);
    header.setReorderingAllowed(false);
    tablaPlanEstudios.setGridColor(new java.awt.Color(230, 230, 230));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    panelCentral.add(jScrollPane1, gridBagConstraints);
    jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
    jScrollPane1.setBackground(java.awt.Color.WHITE);
    jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());

    panelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

    javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
    panelInferior.setLayout(panelInferiorLayout);
    panelInferiorLayout.setHorizontalGroup(
        panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );
    panelInferiorLayout.setVerticalGroup(
        panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );

    panelPrincipal.add(panelInferior, java.awt.BorderLayout.SOUTH);

    add(panelPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarBajaActionPerformed
    int filaSeleccionada = tablaPlanEstudios.getSelectedRow();
        if (filaSeleccionada < 0 || cursosCargados == null) {
            mostrarMensaje("Seleccione un curso de la tabla para darle de baja.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String codigoFila = (String) tablaPlanEstudios.getValueAt(filaSeleccionada, 0);
        Curso seleccionado = null;
        
        for (int i = 0; i < cursosCargados.size(); i++) {
            if (cursosCargados.get(i).getCodigo().equals(codigoFila)) {
                seleccionado = cursosCargados.get(i);
                break;
            }
        }

        if (seleccionado == null || cursoController == null) return;

        int confirmar = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "¿Está seguro de que desea dar de baja el curso " + seleccionado.getNombre() + "?\n" +
            "Esta operación cambiará su estado a INACTIVO.",
            "Confirmar Baja Lógica",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            if (cursoController.darDeBajaCurso(seleccionado)) {
                mostrarMensaje("El curso ha sido dado de baja correctamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                refrescarTabla(cursoController.obtenerCursos());
            } else {
                mostrarMensaje("No se pudo procesar el cambio de estado.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }        
    }//GEN-LAST:event_btnDarBajaActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        ejecutarFiltroBusqueda();
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnNuevoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCursoActionPerformed
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof java.awt.Frame frame && cursoController != null) {
            
            plan_estudios.controller.GradoController gradoController = new plan_estudios.controller.GradoController();
            docentes.controller.DocenteController docenteController = new docentes.controller.DocenteController();
            
            List<Grado> grados = gradoController.obtenerGradosActivos();
            List<Docente> docentes = docenteController.obtenerDocentes();

            DialogNuevoCurso dialog = new DialogNuevoCurso(frame, true, cursoController, this, null, grados, docentes);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_btnNuevoCursoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ejecutarFiltroBusqueda();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaPlanEstudiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPlanEstudiosMouseClicked
        if (evt.getClickCount() == 2) {
            int filaSeleccionada = tablaPlanEstudios.getSelectedRow();
            if (filaSeleccionada >= 0 && cursosCargados != null) {
                String codigoFila = (String) tablaPlanEstudios.getValueAt(filaSeleccionada, 0);
                Curso seleccionado = null;
                
                for (int i = 0; i < cursosCargados.size(); i++) {
                    if (cursosCargados.get(i).getCodigo().equals(codigoFila)) {
                        seleccionado = cursosCargados.get(i);
                        break;
                    }
                }
                
                if (seleccionado != null) {
                    abrirDialogoEdicion(seleccionado);
                }
            }
        }
    }//GEN-LAST:event_tablaPlanEstudiosMouseClicked

    private void ejecutarFiltroBusqueda() {
        if (cursoController != null) {
            String codigoBusqueda = txtBuscar.getText().trim();
            List<Curso> resultados = cursoController.buscarPorCodigo(codigoBusqueda);
            
            if (resultados.isEmpty() && !codigoBusqueda.isEmpty() && !codigoBusqueda.equals("Buscar por Código")) {
                refrescarTabla(Collections.emptyList());
                mostrarMensaje("No se encontró ningún curso con el código: " + codigoBusqueda, "Búsqueda", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                refrescarTabla(resultados);
            }
        }
    }

    public void mostrarMensaje(String mensaje, String titulo, int tipoMensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, titulo, tipoMensaje);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDarBaja;
    private javax.swing.JButton btnNuevoCurso;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombrePanel;
    private javax.swing.JPanel panelAgregar;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTable tablaPlanEstudios;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
