
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package plan_estudios.view;
import docentes.controller.DocenteController;
import docentes.model.Docente;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import plan_estudios.controller.PlanEstudiosController;
import plan_estudios.model.Curso;
import plan_estudios.model.Grado;

/**
 *
 * @author Alexis
 */
public class PanelPlanEstudios extends javax.swing.JPanel {

    private final PlanEstudiosController planEstudiosController;
    private final DocenteController docenteController;
    private List<Curso> cursosCargados = new ArrayList<>();
    
    /**
     * Creates new form PanelAlumnos
     */
    public PanelPlanEstudios() {
        this.planEstudiosController = null;
        this.docenteController = null;
        initComponents();
        this.setBackground(java.awt.Color.WHITE);
    }
     
    public PanelPlanEstudios(PlanEstudiosController planEstudiosController, DocenteController docenteController) {
        this.planEstudiosController = planEstudiosController;
        this.docenteController = docenteController;
        initComponents();
        this.setBackground(java.awt.Color.WHITE);
        if (this.planEstudiosController != null) {
            javax.swing.SwingUtilities.invokeLater(() -> refrescarTabla(planEstudiosController.obtenerCursos()));
        }
    }
    
    public void recargarDatos() {
        if (planEstudiosController == null) return;

        String seleccionActual = (String) cboEstado.getSelectedItem();

        List<Curso> datosActualizados = planEstudiosController.obtenerCursosPorEstado(seleccionActual);

        refrescarTabla(datosActualizados);
    }

    public void refrescarTabla(List<Curso> cursos) {
        this.cursosCargados = (cursos != null) ? cursos : Collections.emptyList();
        DefaultTableModel modelo = (DefaultTableModel) tablaPlanEstudios.getModel();
        modelo.setRowCount(0);

        for (Curso c : this.cursosCargados) {
            modelo.addRow(new Object[]{
                c.getCodigo(),
                c.getNombre(),
                c.getGradoAsignado() != null ? c.getGradoAsignado().getNombre() + " - " + c.getGradoAsignado().getNivel() : "No asignado",
                c.getHorasSemanales(),
                c.getDocente() != null ? c.getDocente().getNombreCompleto() : "Por asignar",
                c.isActivo() ? "ACTIVO" : "INACTIVO"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelNombre = new javax.swing.JPanel();
        nombrePanel = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 32767));
        panelAccionesCurso = new javax.swing.JPanel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnEstadoCurso = new javax.swing.JButton();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnEdicionCurso = new javax.swing.JButton();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnNuevo = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        panelBusqueda = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        cboEstado = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnBuscar = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        panelCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPlanEstudios = new javax.swing.JTable();
        panelInferior = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout());

        panelPrincipal.setOpaque(false);
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setOpaque(false);
        panelSuperior.setLayout(new javax.swing.BoxLayout(panelSuperior, javax.swing.BoxLayout.Y_AXIS));

        panelNombre.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelNombre.setMinimumSize(new java.awt.Dimension(400, 30));
        panelNombre.setOpaque(false);
        panelNombre.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelNombre.setLayout(new java.awt.BorderLayout());

        nombrePanel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nombrePanel.setText("Plan de Estudios");
        nombrePanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNombre.add(nombrePanel, java.awt.BorderLayout.WEST);

        panelSuperior.add(panelNombre);
        panelSuperior.add(filler4);

        panelAccionesCurso.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelAccionesCurso.setMinimumSize(new java.awt.Dimension(400, 35));
        panelAccionesCurso.setOpaque(false);
        panelAccionesCurso.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelAccionesCurso.setLayout(new javax.swing.BoxLayout(panelAccionesCurso, javax.swing.BoxLayout.X_AXIS));
        panelAccionesCurso.add(filler10);

        btnEstadoCurso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEstadoCurso.setText("Dar baja Curso");
        btnEstadoCurso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstadoCurso.setMaximumSize(new java.awt.Dimension(140, 35));
        btnEstadoCurso.setMinimumSize(new java.awt.Dimension(140, 35));
        btnEstadoCurso.setPreferredSize(new java.awt.Dimension(140, 35));
        btnEstadoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoCursoActionPerformed(evt);
            }
        });
        panelAccionesCurso.add(btnEstadoCurso);
        panelAccionesCurso.add(filler11);

        btnEdicionCurso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEdicionCurso.setText("Editar Curso");
        btnEdicionCurso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdicionCurso.setMaximumSize(new java.awt.Dimension(140, 35));
        btnEdicionCurso.setMinimumSize(new java.awt.Dimension(140, 35));
        btnEdicionCurso.setPreferredSize(new java.awt.Dimension(140, 35));
        btnEdicionCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdicionCursoActionPerformed(evt);
            }
        });
        panelAccionesCurso.add(btnEdicionCurso);
        panelAccionesCurso.add(filler12);

        btnNuevo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNuevo.setText("Nuevo Curso");
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setMaximumSize(new java.awt.Dimension(140, 35));
        btnNuevo.setMinimumSize(new java.awt.Dimension(140, 35));
        btnNuevo.setPreferredSize(new java.awt.Dimension(140, 35));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panelAccionesCurso.add(btnNuevo);

        panelSuperior.add(panelAccionesCurso);
        panelSuperior.add(filler3);

        panelBusqueda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelBusqueda.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelBusqueda.setMinimumSize(new java.awt.Dimension(400, 35));
        panelBusqueda.setOpaque(false);
        panelBusqueda.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelBusqueda.setLayout(new javax.swing.BoxLayout(panelBusqueda, javax.swing.BoxLayout.X_AXIS));

        txtBuscar.setText("Buscar por Código");
        txtBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        txtBuscar.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtBuscar.setMinimumSize(new java.awt.Dimension(250, 35));
        txtBuscar.setName(""); // NOI18N
        txtBuscar.setPreferredSize(new java.awt.Dimension(250, 35));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        panelBusqueda.add(txtBuscar);
        txtBuscar.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)),
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
    panelBusqueda.add(filler5);

    cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "ACTIVOS", "INACTIVOS" }));
    cboEstado.setMinimumSize(new java.awt.Dimension(72, 35));
    cboEstado.setPreferredSize(new java.awt.Dimension(72, 35));
    cboEstado.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cboEstadoActionPerformed(evt);
        }
    });
    panelBusqueda.add(cboEstado);
    panelBusqueda.add(filler1);

    btnBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    btnBuscar.setText("Buscar");
    btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnBuscar.setMaximumSize(new java.awt.Dimension(140, 35));
    btnBuscar.setMinimumSize(new java.awt.Dimension(140, 35));
    btnBuscar.setPreferredSize(new java.awt.Dimension(140, 35));
    btnBuscar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBuscarActionPerformed(evt);
        }
    });
    panelBusqueda.add(btnBuscar);

    panelSuperior.add(panelBusqueda);
    panelSuperior.add(filler2);

    panelPrincipal.add(panelSuperior, java.awt.BorderLayout.NORTH);

    panelCentral.setLayout(new java.awt.GridBagLayout());

    tablaPlanEstudios.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null}
        },
        new String [] {
            "Codigo", "Nombre", "Grado", "Horas Semanales", "Docente Asignado", "Estado del Curso"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    tablaPlanEstudios.setFillsViewportHeight(true);
    tablaPlanEstudios.setOpaque(false);
    tablaPlanEstudios.setRowHeight(40);
    tablaPlanEstudios.setShowGrid(false);
    tablaPlanEstudios.setShowHorizontalLines(true);
    tablaPlanEstudios.getTableHeader().setReorderingAllowed(false);
    tablaPlanEstudios.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tablaPlanEstudiosMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(tablaPlanEstudios);
    if (tablaPlanEstudios.getColumnModel().getColumnCount() > 0) {
        tablaPlanEstudios.getColumnModel().getColumn(0).setResizable(false);
        tablaPlanEstudios.getColumnModel().getColumn(1).setResizable(false);
        tablaPlanEstudios.getColumnModel().getColumn(2).setResizable(false);
        tablaPlanEstudios.getColumnModel().getColumn(3).setResizable(false);
        tablaPlanEstudios.getColumnModel().getColumn(4).setResizable(false);
        tablaPlanEstudios.getColumnModel().getColumn(5).setResizable(false);
    }
    javax.swing.table.JTableHeader header = tablaPlanEstudios.getTableHeader();
    header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    header.setBackground(new java.awt.Color(245, 245, 245)); // Gris muy claro
    header.setOpaque(true);
    header.setReorderingAllowed(false);
    tablaPlanEstudios.setGridColor(new java.awt.Color(230, 230, 230));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    panelCentral.add(jScrollPane1, gridBagConstraints);
    jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
    jScrollPane1.setBackground(java.awt.Color.WHITE);
    jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());

    panelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

    javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
    panelInferior.setLayout(panelInferiorLayout);
    panelInferiorLayout.setHorizontalGroup(
        panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );
    panelInferiorLayout.setVerticalGroup(
        panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );

    panelPrincipal.add(panelInferior, java.awt.BorderLayout.SOUTH);

    add(panelPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        ejecutarFiltroBusqueda();
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ejecutarFiltroBusqueda();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaPlanEstudiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPlanEstudiosMouseClicked
        int fila = tablaPlanEstudios.getSelectedRow();
        if (fila != -1) {
            String estado = (String) tablaPlanEstudios.getValueAt(fila, 5);
            btnEstadoCurso.setText(estado.equals("ACTIVO") ? "Dar de Baja" : "Reactivar Curso");
        }
    }//GEN-LAST:event_tablaPlanEstudiosMouseClicked

    private void btnEstadoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoCursoActionPerformed
    int filaSeleccionada = tablaPlanEstudios.getSelectedRow();
    if (filaSeleccionada == -1) {
        mostrarError("Por favor, seleccione un curso de la tabla.");
        return;
    }

    String codigo = (String) tablaPlanEstudios.getValueAt(filaSeleccionada, 0);
    String estadoActual = (String) tablaPlanEstudios.getValueAt(filaSeleccionada, 5); // Columna 5 es "Estado del Curso"

    boolean esReactivacion = estadoActual.equals("INACTIVO");
    String accion = esReactivacion ? "reactivar" : "dar de baja";
    String titulo = esReactivacion ? "Confirmar Reactivación" : "Confirmar Baja";

    int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
        "¿Está seguro de que desea " + accion + " el curso: " + codigo + "?",
        titulo, javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
        String error = esReactivacion 
            ? planEstudiosController.procesarReactivacionPorCodigo(codigo) 
            : planEstudiosController.procesarBajaPorCodigo(codigo);

        if (error == null) {
            String mensajeExito = esReactivacion ? "Curso reactivado correctamente." : "Curso dado de baja correctamente.";
            javax.swing.JOptionPane.showMessageDialog(this, mensajeExito);
            
            recargarDatos(); 
        } else {
            mostrarError(error);
        }
    }
    }//GEN-LAST:event_btnEstadoCursoActionPerformed

    private void btnEdicionCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdicionCursoActionPerformed
    int fila = tablaPlanEstudios.getSelectedRow();
        if (fila == -1) {
            mostrarError("Por favor, seleccione un curso de la tabla para editar.");
            return;
        }

        String codigo = (String) tablaPlanEstudios.getValueAt(fila, 0);
        Curso cursoParaEditar = planEstudiosController.obtenerCursoParaEdicion(codigo);

        if (cursoParaEditar != null) {
            java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
            if (parentWindow instanceof main.VentanaPrincipal main) {
                List<Grado> grados = planEstudiosController.obtenerGradosActivos();
                List<Docente> docentes = docenteController.obtenerDocentesPorEstado("ACTIVOS");
                DialogNuevoCurso dialog = new DialogNuevoCurso(main, true, planEstudiosController, main, cursoParaEditar, grados, docentes);
                dialog.setVisible(true);
            }
        } else {
            mostrarError("No se pudieron cargar los datos del curso. Inténtelo de nuevo.");
        }
    }//GEN-LAST:event_btnEdicionCursoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof main.VentanaPrincipal main) {
            List<Grado> grados = planEstudiosController.obtenerGradosActivos();
            List<Docente> docentes = docenteController.obtenerDocentesPorEstado("ACTIVOS");
            DialogNuevoCurso dialog = new DialogNuevoCurso(main, true, planEstudiosController, main, null, grados, docentes);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void cboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoActionPerformed
        if (planEstudiosController == null) return;

        String seleccion = (String) cboEstado.getSelectedItem();

        List<Curso> resultadosFiltrados = planEstudiosController.obtenerCursosPorEstado(seleccion);

        refrescarTabla(resultadosFiltrados);
    }//GEN-LAST:event_cboEstadoActionPerformed

    private void ejecutarFiltroBusqueda() {
        if (planEstudiosController != null) {
            String codigoBusqueda = txtBuscar.getText().trim();
            List<Curso> resultados = planEstudiosController.buscarCursosPorCodigoBusqueda(codigoBusqueda);
            
            if (resultados.isEmpty() && !codigoBusqueda.isEmpty() && !codigoBusqueda.equals("Buscar por Código")) {
                refrescarTabla(Collections.emptyList());
                mostrarError("No se encontró ningún planEstudios con el código: " + codigoBusqueda);
            } else {
                refrescarTabla(resultados);
            }
        }
    }

    public void mostrarError(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEdicionCurso;
    private javax.swing.JButton btnEstadoCurso;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombrePanel;
    private javax.swing.JPanel panelAccionesCurso;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTable tablaPlanEstudios;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
