package docentes.view;

import docentes.controller.DocenteController;
import docentes.model.Docente;
import java.time.LocalDate;
import java.time.ZoneId;
import main.VentanaPrincipal;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Alexis
 */
public class DialogNuevoDocente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogNuevoDocente.class.getName());
    private final DocenteController docenteController;
    private final PanelDocentes panelPadre;
    private final Docente docenteEdicion;
    
    /**
     * Creates new form DialogNuevoDocente
     * @param parent
     * @param modal
     * @param docenteController
     * @param panelPadre
     * @param docenteEdicion
     */
    public DialogNuevoDocente(java.awt.Frame parent, boolean modal, DocenteController docenteController, PanelDocentes panelPadre, Docente docenteEdicion) {
        super(parent, modal);
        this.docenteController = docenteController;
        this.panelPadre = panelPadre;
        this.docenteEdicion = docenteEdicion;
        initComponents();
        this.setLocationRelativeTo(parent);
        if (this.docenteEdicion != null) {
            cargarDatosEnFormulario();
        }
    }
    
    private void cargarDatosEnFormulario() {
        nombrePanel.setText("Modificar Información del Docente");
        txtDniAlumno.setText(docenteEdicion.getDni());
        txtDniAlumno.setEditable(false); 
        txtNombresAlumno.setText(docenteEdicion.getNombres());
        txtApellidosAlumno.setText(docenteEdicion.getApellidos());
        txtTituloProfesional.setText(docenteEdicion.getTituloProfesional());
        txtEspecialidadAcademica.setText(docenteEdicion.getEspecialidadAcademica());
        txtTelefono.setText(docenteEdicion.getTelefono());
        txtCorreo.setText(docenteEdicion.getCorreo());

        if (docenteEdicion.getFechaNacimiento() != null) {
            spinFechaNacimiento.setValue(java.util.Date.from(docenteEdicion.getFechaNacimiento()
                    .atStartOfDay(java.time.ZoneId.systemDefault()).toInstant()));
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        nombrePanel = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        panelDatosDocente = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        panelRowDni = new javax.swing.JPanel();
        lblDniAlumno = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtDniAlumno = new javax.swing.JTextField();
        panelRowNombres = new javax.swing.JPanel();
        lblNombresAlumno = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtNombresAlumno = new javax.swing.JTextField();
        panelRowApellidos = new javax.swing.JPanel();
        lblApellidosAlumno = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtApellidosAlumno = new javax.swing.JTextField();
        panelRowFechaNacimiento = new javax.swing.JPanel();
        lblFechaNacimientoAlumno = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        spinFechaNacimiento = new javax.swing.JSpinner();
        panelRowTituloProfesional = new javax.swing.JPanel();
        lblTituloProfesional = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtTituloProfesional = new javax.swing.JTextField();
        panelRowEspecialidadAcademica = new javax.swing.JPanel();
        lblEspecialidadAcademica = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtEspecialidadAcademica = new javax.swing.JTextField();
        panelRowApellidos3 = new javax.swing.JPanel();
        lblTelefono = new javax.swing.JLabel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtTelefono = new javax.swing.JTextField();
        panelRowApellidos4 = new javax.swing.JPanel();
        lblCorreo = new javax.swing.JLabel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtCorreo = new javax.swing.JTextField();
        panelInferior = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        setModal(true);
        setResizable(false);

        panelPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setLayout(new javax.swing.BoxLayout(panelSuperior, javax.swing.BoxLayout.X_AXIS));

        nombrePanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombrePanel.setText("Registrar Nuevo Docente");
        nombrePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        nombrePanel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        nombrePanel.setMaximumSize(new java.awt.Dimension(300, 30));
        nombrePanel.setMinimumSize(new java.awt.Dimension(300, 30));
        nombrePanel.setPreferredSize(new java.awt.Dimension(300, 30));
        panelSuperior.add(nombrePanel);

        panelPrincipal.add(panelSuperior, java.awt.BorderLayout.NORTH);

        panelCentral.setLayout(new java.awt.BorderLayout());

        panelDatosDocente.setLayout(new java.awt.GridBagLayout());
        panelDatosDocente.add(filler1, new java.awt.GridBagConstraints());

        panelRowDni.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowDni.setMaximumSize(new java.awt.Dimension(32767, 45));
        panelRowDni.setOpaque(false);
        panelRowDni.setLayout(new javax.swing.BoxLayout(panelRowDni, javax.swing.BoxLayout.X_AXIS));

        lblDniAlumno.setText("DNI");
        lblDniAlumno.setMaximumSize(new java.awt.Dimension(150, 30));
        lblDniAlumno.setMinimumSize(new java.awt.Dimension(150, 30));
        lblDniAlumno.setPreferredSize(new java.awt.Dimension(150, 30));
        panelRowDni.add(lblDniAlumno);
        panelRowDni.add(filler3);

        txtDniAlumno.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtDniAlumno.setMinimumSize(new java.awt.Dimension(250, 35));
        txtDniAlumno.setPreferredSize(new java.awt.Dimension(250, 35));
        txtDniAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniAlumnoActionPerformed(evt);
            }
        });
        panelRowDni.add(txtDniAlumno);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosDocente.add(panelRowDni, gridBagConstraints);

        panelRowNombres.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowNombres.setOpaque(false);
        panelRowNombres.setLayout(new javax.swing.BoxLayout(panelRowNombres, javax.swing.BoxLayout.X_AXIS));

        lblNombresAlumno.setText("Nombres");
        lblNombresAlumno.setMaximumSize(new java.awt.Dimension(150, 30));
        lblNombresAlumno.setMinimumSize(new java.awt.Dimension(150, 30));
        lblNombresAlumno.setPreferredSize(new java.awt.Dimension(150, 30));
        panelRowNombres.add(lblNombresAlumno);
        panelRowNombres.add(filler4);

        txtNombresAlumno.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtNombresAlumno.setMinimumSize(new java.awt.Dimension(250, 35));
        txtNombresAlumno.setPreferredSize(new java.awt.Dimension(250, 35));
        panelRowNombres.add(txtNombresAlumno);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosDocente.add(panelRowNombres, gridBagConstraints);

        panelRowApellidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowApellidos.setOpaque(false);
        panelRowApellidos.setLayout(new javax.swing.BoxLayout(panelRowApellidos, javax.swing.BoxLayout.X_AXIS));

        lblApellidosAlumno.setText("Apellidos");
        lblApellidosAlumno.setMaximumSize(new java.awt.Dimension(150, 30));
        lblApellidosAlumno.setMinimumSize(new java.awt.Dimension(150, 30));
        lblApellidosAlumno.setPreferredSize(new java.awt.Dimension(150, 30));
        panelRowApellidos.add(lblApellidosAlumno);
        panelRowApellidos.add(filler5);

        txtApellidosAlumno.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtApellidosAlumno.setMinimumSize(new java.awt.Dimension(250, 35));
        txtApellidosAlumno.setPreferredSize(new java.awt.Dimension(250, 35));
        panelRowApellidos.add(txtApellidosAlumno);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosDocente.add(panelRowApellidos, gridBagConstraints);

        panelRowFechaNacimiento.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowFechaNacimiento.setOpaque(false);
        panelRowFechaNacimiento.setLayout(new javax.swing.BoxLayout(panelRowFechaNacimiento, javax.swing.BoxLayout.X_AXIS));

        lblFechaNacimientoAlumno.setText("Fecha de Nacimiento");
        lblFechaNacimientoAlumno.setMaximumSize(new java.awt.Dimension(150, 30));
        lblFechaNacimientoAlumno.setMinimumSize(new java.awt.Dimension(150, 30));
        lblFechaNacimientoAlumno.setPreferredSize(new java.awt.Dimension(150, 30));
        panelRowFechaNacimiento.add(lblFechaNacimientoAlumno);
        panelRowFechaNacimiento.add(filler6);

        spinFechaNacimiento.setModel(new javax.swing.SpinnerDateModel());
        spinFechaNacimiento.setEditor(new javax.swing.JSpinner.DateEditor(spinFechaNacimiento, "dd/MM/yyyy"));
        spinFechaNacimiento.setMaximumSize(new java.awt.Dimension(32767, 35));
        spinFechaNacimiento.setMinimumSize(new java.awt.Dimension(250, 35));
        spinFechaNacimiento.setPreferredSize(new java.awt.Dimension(250, 35));
        panelRowFechaNacimiento.add(spinFechaNacimiento);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosDocente.add(panelRowFechaNacimiento, gridBagConstraints);

        panelRowTituloProfesional.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowTituloProfesional.setOpaque(false);
        panelRowTituloProfesional.setLayout(new javax.swing.BoxLayout(panelRowTituloProfesional, javax.swing.BoxLayout.X_AXIS));

        lblTituloProfesional.setText("Título Profesional");
        lblTituloProfesional.setMaximumSize(new java.awt.Dimension(150, 30));
        lblTituloProfesional.setMinimumSize(new java.awt.Dimension(150, 30));
        lblTituloProfesional.setPreferredSize(new java.awt.Dimension(150, 30));
        panelRowTituloProfesional.add(lblTituloProfesional);
        panelRowTituloProfesional.add(filler8);

        txtTituloProfesional.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtTituloProfesional.setMinimumSize(new java.awt.Dimension(250, 35));
        txtTituloProfesional.setPreferredSize(new java.awt.Dimension(250, 35));
        panelRowTituloProfesional.add(txtTituloProfesional);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosDocente.add(panelRowTituloProfesional, gridBagConstraints);

        panelRowEspecialidadAcademica.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowEspecialidadAcademica.setOpaque(false);
        panelRowEspecialidadAcademica.setLayout(new javax.swing.BoxLayout(panelRowEspecialidadAcademica, javax.swing.BoxLayout.X_AXIS));

        lblEspecialidadAcademica.setText("Especialidad Academica");
        lblEspecialidadAcademica.setMaximumSize(new java.awt.Dimension(150, 30));
        lblEspecialidadAcademica.setMinimumSize(new java.awt.Dimension(150, 30));
        lblEspecialidadAcademica.setPreferredSize(new java.awt.Dimension(150, 30));
        panelRowEspecialidadAcademica.add(lblEspecialidadAcademica);
        panelRowEspecialidadAcademica.add(filler9);

        txtEspecialidadAcademica.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtEspecialidadAcademica.setMinimumSize(new java.awt.Dimension(250, 35));
        txtEspecialidadAcademica.setPreferredSize(new java.awt.Dimension(250, 35));
        panelRowEspecialidadAcademica.add(txtEspecialidadAcademica);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosDocente.add(panelRowEspecialidadAcademica, gridBagConstraints);

        panelRowApellidos3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowApellidos3.setOpaque(false);
        panelRowApellidos3.setLayout(new javax.swing.BoxLayout(panelRowApellidos3, javax.swing.BoxLayout.X_AXIS));

        lblTelefono.setText("Telefono");
        lblTelefono.setMaximumSize(new java.awt.Dimension(150, 30));
        lblTelefono.setMinimumSize(new java.awt.Dimension(150, 30));
        lblTelefono.setPreferredSize(new java.awt.Dimension(150, 30));
        panelRowApellidos3.add(lblTelefono);
        panelRowApellidos3.add(filler10);

        txtTelefono.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtTelefono.setMinimumSize(new java.awt.Dimension(250, 35));
        txtTelefono.setPreferredSize(new java.awt.Dimension(250, 35));
        panelRowApellidos3.add(txtTelefono);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosDocente.add(panelRowApellidos3, gridBagConstraints);

        panelRowApellidos4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowApellidos4.setOpaque(false);
        panelRowApellidos4.setLayout(new javax.swing.BoxLayout(panelRowApellidos4, javax.swing.BoxLayout.X_AXIS));

        lblCorreo.setText("Correo");
        lblCorreo.setMaximumSize(new java.awt.Dimension(150, 30));
        lblCorreo.setMinimumSize(new java.awt.Dimension(150, 30));
        lblCorreo.setPreferredSize(new java.awt.Dimension(150, 30));
        panelRowApellidos4.add(lblCorreo);
        panelRowApellidos4.add(filler11);

        txtCorreo.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtCorreo.setMinimumSize(new java.awt.Dimension(250, 35));
        txtCorreo.setPreferredSize(new java.awt.Dimension(250, 35));
        panelRowApellidos4.add(txtCorreo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosDocente.add(panelRowApellidos4, gridBagConstraints);

        panelCentral.add(panelDatosDocente, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

        panelInferior.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelInferior.setLayout(new javax.swing.BoxLayout(panelInferior, javax.swing.BoxLayout.X_AXIS));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(100, 35));
        btnCancelar.setMinimumSize(new java.awt.Dimension(100, 35));
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 35));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelInferior.add(btnCancelar);
        panelInferior.add(filler7);

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(100, 35));
        btnGuardar.setMinimumSize(new java.awt.Dimension(100, 35));
        btnGuardar.setPreferredSize(new java.awt.Dimension(100, 35));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelInferior.add(btnGuardar);

        panelPrincipal.add(panelInferior, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDniAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniAlumnoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            final boolean exito = (docenteEdicion != null) 
                ? docenteController.actualizarDocente(actualizarDocenteDesdeFormulario())
                : docenteController.registrarDocente(obtenerDocenteDesdeFormulario());

            if (exito) {
                if (panelPadre != null) panelPadre.refrescarTabla(docenteController.obtenerDocentes());
                this.dispose();
            } else {
                mostrarMensajeValidacion("No se pudo guardar el registro. Verifique los datos o la conexión.");
            }
        } catch (IllegalArgumentException | IllegalStateException e) {
            mostrarMensajeValidacion(e.getMessage());
        } catch (RuntimeException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error crítico de sistema al guardar", e);
            mostrarMensajeValidacion("Ocurrió un error inesperado de sistema. Consulte con soporte.");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private Docente obtenerDocenteDesdeFormulario() {
        LocalDate nacDocente = ((java.util.Date) spinFechaNacimiento.getValue()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        return new Docente("TEMP", txtTituloProfesional.getText().trim(), txtEspecialidadAcademica.getText().trim(), 
                           txtCorreo.getText().trim(), txtTelefono.getText().trim(), null, txtDniAlumno.getText().trim(), 
                           txtNombresAlumno.getText().trim(), txtApellidosAlumno.getText().trim(), nacDocente, true);
    }

    private Docente actualizarDocenteDesdeFormulario() {
        Docente docMod = new Docente();
        docMod.setId(docenteEdicion.getId());
        docMod.setCodigoDocente(docenteEdicion.getCodigoDocente());
        docMod.setDni(txtDniAlumno.getText().trim());
        docMod.setNombres(txtNombresAlumno.getText().trim());
        docMod.setApellidos(txtApellidosAlumno.getText().trim());
        docMod.setTituloProfesional(txtTituloProfesional.getText().trim());
        docMod.setEspecialidadAcademica(txtEspecialidadAcademica.getText().trim());
        docMod.actualizarContacto(txtTelefono.getText().trim(), txtCorreo.getText().trim());
        docMod.setFechaNacimiento(((java.util.Date) spinFechaNacimiento.getValue()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        docMod.setActivo(docenteEdicion.isActivo()); 

        return docMod;
    }
    
    public void mostrarMensajeValidacion(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "No se pudo aplicar el tema nativo del sistema", ex);
        }

        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel lblApellidosAlumno;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDniAlumno;
    private javax.swing.JLabel lblEspecialidadAcademica;
    private javax.swing.JLabel lblFechaNacimientoAlumno;
    private javax.swing.JLabel lblNombresAlumno;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloProfesional;
    private javax.swing.JLabel nombrePanel;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelDatosDocente;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRowApellidos;
    private javax.swing.JPanel panelRowApellidos3;
    private javax.swing.JPanel panelRowApellidos4;
    private javax.swing.JPanel panelRowDni;
    private javax.swing.JPanel panelRowEspecialidadAcademica;
    private javax.swing.JPanel panelRowFechaNacimiento;
    private javax.swing.JPanel panelRowNombres;
    private javax.swing.JPanel panelRowTituloProfesional;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JSpinner spinFechaNacimiento;
    private javax.swing.JTextField txtApellidosAlumno;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDniAlumno;
    private javax.swing.JTextField txtEspecialidadAcademica;
    private javax.swing.JTextField txtNombresAlumno;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTituloProfesional;
    // End of variables declaration//GEN-END:variables
}
