package docentes.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import docentes.controller.DocenteController;
import docentes.model.Docente;
import java.util.Collections;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Alexis
 */
public class PanelDocentes extends javax.swing.JPanel {
    private final DocenteController docenteController;
    private List<Docente> docentesCargados;
    
    /**
     * Creates new form PanelDocentes
     */
    public PanelDocentes() {
        this.docenteController = null;
        initComponents();
        this.setBackground(java.awt.Color.WHITE);
    }

    public PanelDocentes(DocenteController docenteController) {
        this.docenteController = docenteController;
        initComponents();
        this.setBackground(java.awt.Color.WHITE);

        if (this.docenteController != null) {
            javax.swing.SwingUtilities.invokeLater(() -> refrescarTabla(docenteController.obtenerDocentes()));
        }
    }
    
    public void recargarDatos() {
        if (docenteController == null) return;

        String seleccionActual = (String) cboEstado.getSelectedItem();

        List<Docente> datosActualizados = docenteController.obtenerDocentesPorEstado(seleccionActual);

        refrescarTabla(datosActualizados);
    }

    public void refrescarTabla(List<Docente> docentes) {
        this.docentesCargados = (docentes != null) ? docentes : Collections.emptyList();
        DefaultTableModel modelo = (DefaultTableModel) tablaDocentes.getModel();
        modelo.setRowCount(0);

        for (Docente d : this.docentesCargados) {
            modelo.addRow(new Object[]{
                d.getCodigoDocente(),
                d.getDni(),
                d.getNombreCompleto(),
                d.getEspecialidadAcademica(),
                d.getTelefono(),
                d.isActivo() ? "ACTIVO" : "CESADO"
            });
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelNombre = new javax.swing.JPanel();
        nombrePanel = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 32767));
        panelAccionesDocentes = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnEstadoDocente = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnEdicionDocente = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnNuevo = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        panelBusqueda = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        cboEstado = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnBuscar = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        panelCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDocentes = new javax.swing.JTable();
        panelInferior = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout());

        panelPrincipal.setOpaque(false);
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setOpaque(false);
        panelSuperior.setLayout(new javax.swing.BoxLayout(panelSuperior, javax.swing.BoxLayout.Y_AXIS));

        panelNombre.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelNombre.setMinimumSize(new java.awt.Dimension(400, 30));
        panelNombre.setOpaque(false);
        panelNombre.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelNombre.setLayout(new java.awt.BorderLayout());

        nombrePanel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nombrePanel.setText("Gestión de Docentes");
        nombrePanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNombre.add(nombrePanel, java.awt.BorderLayout.WEST);

        panelSuperior.add(panelNombre);
        panelSuperior.add(filler4);

        panelAccionesDocentes.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelAccionesDocentes.setMinimumSize(new java.awt.Dimension(400, 35));
        panelAccionesDocentes.setOpaque(false);
        panelAccionesDocentes.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelAccionesDocentes.setLayout(new javax.swing.BoxLayout(panelAccionesDocentes, javax.swing.BoxLayout.X_AXIS));
        panelAccionesDocentes.add(filler6);

        btnEstadoDocente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEstadoDocente.setText("Dar de Baja");
        btnEstadoDocente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstadoDocente.setMaximumSize(new java.awt.Dimension(140, 35));
        btnEstadoDocente.setMinimumSize(new java.awt.Dimension(140, 35));
        btnEstadoDocente.setPreferredSize(new java.awt.Dimension(140, 35));
        btnEstadoDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoDocenteActionPerformed(evt);
            }
        });
        panelAccionesDocentes.add(btnEstadoDocente);
        panelAccionesDocentes.add(filler8);

        btnEdicionDocente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEdicionDocente.setText("Editar Docente");
        btnEdicionDocente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdicionDocente.setMaximumSize(new java.awt.Dimension(140, 35));
        btnEdicionDocente.setMinimumSize(new java.awt.Dimension(140, 35));
        btnEdicionDocente.setPreferredSize(new java.awt.Dimension(140, 35));
        btnEdicionDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdicionDocenteActionPerformed(evt);
            }
        });
        panelAccionesDocentes.add(btnEdicionDocente);
        panelAccionesDocentes.add(filler7);

        btnNuevo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNuevo.setText("Nuevo Docente");
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setMaximumSize(new java.awt.Dimension(140, 35));
        btnNuevo.setMinimumSize(new java.awt.Dimension(140, 35));
        btnNuevo.setPreferredSize(new java.awt.Dimension(140, 35));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panelAccionesDocentes.add(btnNuevo);

        panelSuperior.add(panelAccionesDocentes);
        panelSuperior.add(filler2);

        panelBusqueda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelBusqueda.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelBusqueda.setMinimumSize(new java.awt.Dimension(400, 35));
        panelBusqueda.setOpaque(false);
        panelBusqueda.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelBusqueda.setLayout(new javax.swing.BoxLayout(panelBusqueda, javax.swing.BoxLayout.LINE_AXIS));

        txtBuscar.setText("Buscar por Código");
        txtBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        txtBuscar.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtBuscar.setMinimumSize(new java.awt.Dimension(250, 35));
        txtBuscar.setName(""); // NOI18N
        txtBuscar.setPreferredSize(new java.awt.Dimension(250, 35));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        panelBusqueda.add(txtBuscar);
        txtBuscar.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)),
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
    panelBusqueda.add(filler5);

    cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "ACTIVOS", "CESADOS" }));
    cboEstado.setMinimumSize(new java.awt.Dimension(72, 35));
    cboEstado.setPreferredSize(new java.awt.Dimension(72, 35));
    cboEstado.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cboEstadoActionPerformed(evt);
        }
    });
    panelBusqueda.add(cboEstado);
    panelBusqueda.add(filler1);

    btnBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    btnBuscar.setText("Buscar");
    btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnBuscar.setMaximumSize(new java.awt.Dimension(140, 35));
    btnBuscar.setMinimumSize(new java.awt.Dimension(140, 35));
    btnBuscar.setPreferredSize(new java.awt.Dimension(140, 35));
    btnBuscar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBuscarActionPerformed(evt);
        }
    });
    panelBusqueda.add(btnBuscar);

    panelSuperior.add(panelBusqueda);
    panelSuperior.add(filler3);

    panelPrincipal.add(panelSuperior, java.awt.BorderLayout.NORTH);

    panelCentral.setLayout(new java.awt.GridBagLayout());

    tablaDocentes.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null}
        },
        new String [] {
            "Codigo", "DNI", "Nombre Completo", "Especialidad", "Teléfono", "Estado"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    tablaDocentes.setFillsViewportHeight(true);
    tablaDocentes.setOpaque(false);
    tablaDocentes.setRowHeight(40);
    tablaDocentes.setShowGrid(false);
    tablaDocentes.setShowHorizontalLines(true);
    tablaDocentes.getTableHeader().setReorderingAllowed(false);
    tablaDocentes.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tablaDocentesMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(tablaDocentes);
    if (tablaDocentes.getColumnModel().getColumnCount() > 0) {
        tablaDocentes.getColumnModel().getColumn(0).setResizable(false);
        tablaDocentes.getColumnModel().getColumn(1).setResizable(false);
        tablaDocentes.getColumnModel().getColumn(2).setResizable(false);
        tablaDocentes.getColumnModel().getColumn(3).setResizable(false);
        tablaDocentes.getColumnModel().getColumn(4).setResizable(false);
        tablaDocentes.getColumnModel().getColumn(5).setResizable(false);
    }
    javax.swing.table.JTableHeader header = tablaDocentes.getTableHeader();
    header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    header.setBackground(new java.awt.Color(245, 245, 245)); // Gris muy claro
    header.setOpaque(true);
    header.setReorderingAllowed(false);
    tablaDocentes.setGridColor(new java.awt.Color(230, 230, 230));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    panelCentral.add(jScrollPane1, gridBagConstraints);
    jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
    jScrollPane1.setBackground(java.awt.Color.WHITE);
    jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());

    panelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

    javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
    panelInferior.setLayout(panelInferiorLayout);
    panelInferiorLayout.setHorizontalGroup(
        panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );
    panelInferiorLayout.setVerticalGroup(
        panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );

    panelPrincipal.add(panelInferior, java.awt.BorderLayout.SOUTH);

    add(panelPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaDocentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDocentesMouseClicked
    int fila = tablaDocentes.getSelectedRow();
        if (fila != -1) {
            String estado = (String) tablaDocentes.getValueAt(fila, 5);
            if (estado.equals("ACTIVO")) {
                btnEstadoDocente.setText("Dar de Baja");
            } else {
                btnEstadoDocente.setText("Reactivar Docente");
            }
        }
    }//GEN-LAST:event_tablaDocentesMouseClicked

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        ejecutarBusqueda();
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void cboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoActionPerformed
        if (docenteController == null) return;

        String seleccion = (String) cboEstado.getSelectedItem();

        List<Docente> resultadosFiltrados = docenteController.obtenerDocentesPorEstado(seleccion);

        refrescarTabla(resultadosFiltrados);
    }//GEN-LAST:event_cboEstadoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ejecutarBusqueda();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEstadoDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoDocenteActionPerformed
        int filaSeleccionada = tablaDocentes.getSelectedRow();
        if (filaSeleccionada == -1) {
            mostrarError("Por favor, seleccione un docente de la tabla.");
            return;
        }

        String codigo = (String) tablaDocentes.getValueAt(filaSeleccionada, 0);
        String estadoActual = (String) tablaDocentes.getValueAt(filaSeleccionada, 5);

        boolean esReactivacion = estadoActual.equals("CESADO");
        String accion = esReactivacion ? "reactivar" : "dar de baja";
        String titulo = esReactivacion ? "Confirmar Reactivación" : "Confirmar Baja";

        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Está seguro de que desea " + accion + " al docente " + codigo + "?",
            titulo, javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {

            String error = null;
            if (esReactivacion) {
                error = docenteController.procesarReactivacionPorCodigo(codigo);
            } else {
                error = docenteController.procesarBajaPorCodigo(codigo);
            }

            if (error == null) {
                String mensajeExito = esReactivacion ? "Docente reactivado correctamente." : "Docente dado de baja correctamente.";
                javax.swing.JOptionPane.showMessageDialog(this, mensajeExito);
                refrescarTabla(docenteController.obtenerDocentes());

            } else {
                mostrarError(error);
            }
        }
    }//GEN-LAST:event_btnEstadoDocenteActionPerformed

    private void btnEdicionDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdicionDocenteActionPerformed
        int fila = tablaDocentes.getSelectedRow();

        if (fila == -1) {
            mostrarError("Por favor, seleccione un docente de la tabla para editar.");
            return;
        }

        String codigo = (String) tablaDocentes.getValueAt(fila, 0);

        Docente docenteParaEditar = docenteController.obtenerDocenteParaEdicion(codigo);

        if (docenteParaEditar != null) {
            java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
            if (parentWindow instanceof main.VentanaPrincipal main) {
                DialogNuevoDocente dialog = new DialogNuevoDocente(main, true, docenteController, main, docenteParaEditar);
                dialog.setVisible(true);
                
            }
        } else {
            mostrarError("No se pudieron cargar los datos del docente. Inténtelo de nuevo.");
        }
    }//GEN-LAST:event_btnEdicionDocenteActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof main.VentanaPrincipal main) {
            DialogNuevoDocente dialog = new DialogNuevoDocente(main, true, docenteController, main, null);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void ejecutarBusqueda() {
        String codigoBusqueda = txtBuscar.getText().trim();
        List<Docente> resultados = docenteController.buscarDocentesPorCodigoBusqueda(codigoBusqueda);

        if (resultados.isEmpty() && !codigoBusqueda.isEmpty() && !codigoBusqueda.equals("Buscar por Código")) {
            refrescarTabla(java.util.Collections.emptyList());
            mostrarError("No se encontró ningún docente con el código: " + codigoBusqueda);
        } else {
            refrescarTabla(resultados);
        }
    }
    
    public void mostrarError(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEdicionDocente;
    private javax.swing.JButton btnEstadoDocente;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombrePanel;
    private javax.swing.JPanel panelAccionesDocentes;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTable tablaDocentes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
