package docentes.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import docentes.controller.DocenteController;
import docentes.model.Docente;
import java.util.Collections;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Alexis
 */
public class PanelDocentes extends javax.swing.JPanel {
    private final DocenteController docenteController;
    private List<Docente> docentesCargados;
    
    /**
     * Creates new form PanelAlumnos
     */
    public PanelDocentes() {
        this.docenteController = null;
        initComponents();
        this.setBackground(java.awt.Color.WHITE);
    }

    public PanelDocentes(DocenteController docenteController) {
        this.docenteController = docenteController;
        initComponents();
        this.setBackground(java.awt.Color.WHITE);

        if (this.docenteController != null) {
            javax.swing.SwingUtilities.invokeLater(() -> refrescarTabla(docenteController.obtenerDocentes()));
        }
    }

    public void refrescarTabla(List<Docente> docentes) {
        this.docentesCargados = (docentes != null) ? docentes : Collections.emptyList();
        DefaultTableModel modelo = (DefaultTableModel) tablaDocentes.getModel();
        modelo.setRowCount(0);

        for (Docente d : this.docentesCargados) {
            modelo.addRow(new Object[]{
                d.getCodigoDocente(),
                d.getDni(),
                d.getNombreCompleto(),
                d.getEspecialidadAcademica(),
                d.getTelefono(),
                d.isActivo() ? "ACTIVO" : "CESADO"
            });
        }
    }

    private void abrirDialogoEdicion(Docente docenteOriginal) {
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof java.awt.Frame frame) {
            
            Docente copiaDocente = new Docente();
            copiaDocente.setId(docenteOriginal.getId());
            copiaDocente.setCodigoDocente(docenteOriginal.getCodigoDocente());
            copiaDocente.setDni(docenteOriginal.getDni());
            copiaDocente.setNombres(docenteOriginal.getNombres());
            copiaDocente.setApellidos(docenteOriginal.getApellidos());
            copiaDocente.setFechaNacimiento(docenteOriginal.getFechaNacimiento());
            copiaDocente.setTituloProfesional(docenteOriginal.getTituloProfesional());
            copiaDocente.setEspecialidadAcademica(docenteOriginal.getEspecialidadAcademica());
            copiaDocente.actualizarContacto(docenteOriginal.getTelefono(), docenteOriginal.getCorreo());
            copiaDocente.setActivo(docenteOriginal.isActivo());
            
            DialogNuevoDocente dialog = new DialogNuevoDocente(frame, true, docenteController, this, copiaDocente);
            dialog.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelNombre = new javax.swing.JPanel();
        nombrePanel = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 32767));
        panelAgregar = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        panelBusqueda = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnBuscar = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        panelCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDocentes = new javax.swing.JTable();
        panelInferior = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout());

        panelPrincipal.setOpaque(false);
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setOpaque(false);
        panelSuperior.setLayout(new javax.swing.BoxLayout(panelSuperior, javax.swing.BoxLayout.Y_AXIS));

        panelNombre.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelNombre.setMinimumSize(new java.awt.Dimension(400, 30));
        panelNombre.setOpaque(false);
        panelNombre.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelNombre.setLayout(new java.awt.BorderLayout());

        nombrePanel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nombrePanel.setText("Gestión de Docentes");
        nombrePanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNombre.add(nombrePanel, java.awt.BorderLayout.WEST);

        panelSuperior.add(panelNombre);
        panelSuperior.add(filler4);

        panelAgregar.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelAgregar.setMinimumSize(new java.awt.Dimension(400, 35));
        panelAgregar.setOpaque(false);
        panelAgregar.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelAgregar.setLayout(new java.awt.BorderLayout());

        btnNuevo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNuevo.setText("Nuevo Docente");
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setMaximumSize(new java.awt.Dimension(140, 35));
        btnNuevo.setMinimumSize(new java.awt.Dimension(140, 35));
        btnNuevo.setPreferredSize(new java.awt.Dimension(140, 35));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panelAgregar.add(btnNuevo, java.awt.BorderLayout.EAST);

        panelSuperior.add(panelAgregar);
        panelSuperior.add(filler3);

        panelBusqueda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelBusqueda.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelBusqueda.setMinimumSize(new java.awt.Dimension(400, 35));
        panelBusqueda.setOpaque(false);
        panelBusqueda.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelBusqueda.setLayout(new javax.swing.BoxLayout(panelBusqueda, javax.swing.BoxLayout.LINE_AXIS));

        txtBuscar.setText("Buscar por Código");
        txtBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        txtBuscar.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtBuscar.setMinimumSize(new java.awt.Dimension(250, 35));
        txtBuscar.setName(""); // NOI18N
        txtBuscar.setPreferredSize(new java.awt.Dimension(250, 35));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        panelBusqueda.add(txtBuscar);
        txtBuscar.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)),
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
    panelBusqueda.add(filler1);

    btnBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    btnBuscar.setText("Buscar");
    btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnBuscar.setMaximumSize(new java.awt.Dimension(140, 35));
    btnBuscar.setMinimumSize(new java.awt.Dimension(140, 35));
    btnBuscar.setPreferredSize(new java.awt.Dimension(140, 35));
    btnBuscar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBuscarActionPerformed(evt);
        }
    });
    panelBusqueda.add(btnBuscar);

    panelSuperior.add(panelBusqueda);
    panelSuperior.add(filler2);

    panelPrincipal.add(panelSuperior, java.awt.BorderLayout.NORTH);

    panelCentral.setLayout(new java.awt.GridBagLayout());

    tablaDocentes.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null}
        },
        new String [] {
            "Codigo", "DNI", "Nombre Completo", "Especialidad", "Teléfono", "Estado"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    tablaDocentes.setFillsViewportHeight(true);
    tablaDocentes.setOpaque(false);
    tablaDocentes.setRowHeight(40);
    tablaDocentes.setShowGrid(false);
    tablaDocentes.setShowHorizontalLines(true);
    tablaDocentes.getTableHeader().setReorderingAllowed(false);
    tablaDocentes.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tablaDocentesMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(tablaDocentes);
    if (tablaDocentes.getColumnModel().getColumnCount() > 0) {
        tablaDocentes.getColumnModel().getColumn(0).setResizable(false);
        tablaDocentes.getColumnModel().getColumn(1).setResizable(false);
        tablaDocentes.getColumnModel().getColumn(2).setResizable(false);
        tablaDocentes.getColumnModel().getColumn(3).setResizable(false);
        tablaDocentes.getColumnModel().getColumn(4).setResizable(false);
        tablaDocentes.getColumnModel().getColumn(5).setResizable(false);
    }
    javax.swing.table.JTableHeader header = tablaDocentes.getTableHeader();
    header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    header.setBackground(new java.awt.Color(245, 245, 245)); // Gris muy claro
    header.setOpaque(true);
    header.setReorderingAllowed(false);
    tablaDocentes.setGridColor(new java.awt.Color(230, 230, 230));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    panelCentral.add(jScrollPane1, gridBagConstraints);
    jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
    jScrollPane1.setBackground(java.awt.Color.WHITE);
    jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());

    panelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

    javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
    panelInferior.setLayout(panelInferiorLayout);
    panelInferiorLayout.setHorizontalGroup(
        panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );
    panelInferiorLayout.setVerticalGroup(
        panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );

    panelPrincipal.add(panelInferior, java.awt.BorderLayout.SOUTH);

    add(panelPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof java.awt.Frame frame && docenteController != null) {
            DialogNuevoDocente dialog = new DialogNuevoDocente(frame, true, docenteController, this, null);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        ejecutarFiltroBusqueda();
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ejecutarFiltroBusqueda();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaDocentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDocentesMouseClicked
    if (evt.getClickCount() == 2) { 
            int filaSeleccionada = tablaDocentes.getSelectedRow();
            
            if (filaSeleccionada >= 0 && docentesCargados != null) {
                String codigoFila = (String) tablaDocentes.getValueAt(filaSeleccionada, 0);
                Docente docenteSeleccionado = null;
                
                for (int i = 0; i < docentesCargados.size(); i++) {
                    Docente d = docentesCargados.get(i);
                    
                    if (d.getCodigoDocente().equals(codigoFila)) {
                        docenteSeleccionado = d;
                        break;
                    }
                }
                
                if (docenteSeleccionado != null) {
                    abrirDialogoEdicion(docenteSeleccionado);
                }
            }
        }
    }//GEN-LAST:event_tablaDocentesMouseClicked

    private void ejecutarFiltroBusqueda() {
        if (docenteController != null) {
            String codigoBusqueda = txtBuscar.getText().trim();
            List<Docente> resultados = docenteController.buscarPorCodigo(codigoBusqueda);
            
            if (resultados.isEmpty() && !codigoBusqueda.isEmpty() && !codigoBusqueda.equals("Buscar por Código")) {
                refrescarTabla(Collections.emptyList());
                mostrarError("No se encontró ningún docente con el código: " + codigoBusqueda);
            } else {
                refrescarTabla(resultados);
            }
        }
    }
    
    public void mostrarError(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombrePanel;
    private javax.swing.JPanel panelAgregar;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTable tablaDocentes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
