package matricula.view;

import matricula.controller.MatriculaController;
import matricula.model.Matricula;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Alexis
 */
public class PanelMatricula extends javax.swing.JPanel {

    private final MatriculaController matriculaController;
    private List<Matricula> matriculasCargadas = new java.util.ArrayList<>();

    public PanelMatricula() {
        this.matriculaController = null; 
        initComponents(); 
        this.setBackground(java.awt.Color.WHITE);
    }
     
    public PanelMatricula(MatriculaController matriculaController) {
        this.matriculaController = matriculaController;
        initComponents();
        
        this.setBackground(java.awt.Color.WHITE);
        
        if (matriculaController != null) {
            refrescarTabla(matriculaController.obtenerMatriculas());
        }
    }

    private void abrirDetalle(Matricula matriculaSeleccionada) {
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof java.awt.Frame frame && matriculaController != null) {
            DialogNuevaMatricula dialog = new DialogNuevaMatricula(frame, true, matriculaController, this, matriculaSeleccionada);
            dialog.setVisible(true);
        }   
    }

    public void refrescarTabla(List<Matricula> matriculas) {
        this.matriculasCargadas = matriculas; 
        DefaultTableModel modelo = (DefaultTableModel) tablaMatricula.getModel();
        modelo.setRowCount(0); 

        for (Matricula m : matriculas) {
            modelo.addRow(new Object[]{
                m.getCodigoMatricula(),
                m.getAlumno() != null ? m.getAlumno().getDni() : "S/D",
                m.getAlumno() != null ? m.getAlumno().getNombreCompleto() : "S/D",
                m.getAñoEscolar(),
                m.getGrado() != null ? m.getGrado().getNombre() + " - " + m.getGrado().getNivel() : "No asignado",
                m.getFechaMatricula().toString(),
                m.getActivo() ? "ACTIVA" : "ANULADA"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelNombre = new javax.swing.JPanel();
        nombrePanel = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 32767));
        panelAgregar = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnAnularMatricula = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnNuevaMatricula = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        panelBusqueda = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnBuscar = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        panelCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMatricula = new javax.swing.JTable();
        panelInferior = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout());

        panelPrincipal.setOpaque(false);
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setOpaque(false);
        panelSuperior.setLayout(new javax.swing.BoxLayout(panelSuperior, javax.swing.BoxLayout.Y_AXIS));

        panelNombre.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelNombre.setMinimumSize(new java.awt.Dimension(400, 30));
        panelNombre.setOpaque(false);
        panelNombre.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelNombre.setLayout(new java.awt.BorderLayout());

        nombrePanel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nombrePanel.setText("Gestión de Matrícula");
        nombrePanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNombre.add(nombrePanel, java.awt.BorderLayout.WEST);

        panelSuperior.add(panelNombre);
        panelSuperior.add(filler4);

        panelAgregar.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelAgregar.setMinimumSize(new java.awt.Dimension(400, 35));
        panelAgregar.setOpaque(false);
        panelAgregar.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelAgregar.setLayout(new javax.swing.BoxLayout(panelAgregar, javax.swing.BoxLayout.X_AXIS));
        panelAgregar.add(filler5);

        btnAnularMatricula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAnularMatricula.setText("Anular Matrícula");
        btnAnularMatricula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnularMatricula.setMaximumSize(new java.awt.Dimension(140, 35));
        btnAnularMatricula.setMinimumSize(new java.awt.Dimension(140, 35));
        btnAnularMatricula.setPreferredSize(new java.awt.Dimension(140, 35));
        btnAnularMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularMatriculaActionPerformed(evt);
            }
        });
        panelAgregar.add(btnAnularMatricula);
        panelAgregar.add(filler7);

        btnNuevaMatricula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNuevaMatricula.setText("Nueva Matrícula");
        btnNuevaMatricula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevaMatricula.setMaximumSize(new java.awt.Dimension(140, 35));
        btnNuevaMatricula.setMinimumSize(new java.awt.Dimension(140, 35));
        btnNuevaMatricula.setPreferredSize(new java.awt.Dimension(140, 35));
        btnNuevaMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaMatriculaActionPerformed(evt);
            }
        });
        panelAgregar.add(btnNuevaMatricula);

        panelSuperior.add(panelAgregar);
        panelSuperior.add(filler3);

        panelBusqueda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelBusqueda.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelBusqueda.setMinimumSize(new java.awt.Dimension(400, 35));
        panelBusqueda.setOpaque(false);
        panelBusqueda.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelBusqueda.setLayout(new javax.swing.BoxLayout(panelBusqueda, javax.swing.BoxLayout.LINE_AXIS));

        txtBuscar.setText("Buscar por DNI, Codigo o Nombre del Alumno");
        txtBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        txtBuscar.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtBuscar.setMinimumSize(new java.awt.Dimension(250, 35));
        txtBuscar.setName(""); // NOI18N
        txtBuscar.setPreferredSize(new java.awt.Dimension(250, 35));
        txtBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarFocusLost(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        panelBusqueda.add(txtBuscar);
        txtBuscar.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)),
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
    panelBusqueda.add(filler1);

    btnBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    btnBuscar.setText("Buscar");
    btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnBuscar.setMaximumSize(new java.awt.Dimension(140, 35));
    btnBuscar.setMinimumSize(new java.awt.Dimension(140, 35));
    btnBuscar.setPreferredSize(new java.awt.Dimension(140, 35));
    btnBuscar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBuscarActionPerformed(evt);
        }
    });
    panelBusqueda.add(btnBuscar);

    panelSuperior.add(panelBusqueda);
    panelSuperior.add(filler2);

    panelPrincipal.add(panelSuperior, java.awt.BorderLayout.NORTH);

    panelCentral.setLayout(new java.awt.GridBagLayout());

    tablaMatricula.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null}
        },
        new String [] {
            "Codigo", "DNI / Codigo Alumno", "Nombre del Alumno", "Año Académico", "Grado", "Fecha de Matrícula ", "Estado"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    tablaMatricula.setFillsViewportHeight(true);
    tablaMatricula.setOpaque(false);
    tablaMatricula.setRowHeight(40);
    tablaMatricula.setShowGrid(false);
    tablaMatricula.setShowHorizontalLines(true);
    tablaMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tablaMatriculaMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(tablaMatricula);
    if (tablaMatricula.getColumnModel().getColumnCount() > 0) {
        tablaMatricula.getColumnModel().getColumn(0).setResizable(false);
        tablaMatricula.getColumnModel().getColumn(1).setResizable(false);
        tablaMatricula.getColumnModel().getColumn(2).setResizable(false);
        tablaMatricula.getColumnModel().getColumn(3).setResizable(false);
        tablaMatricula.getColumnModel().getColumn(4).setResizable(false);
        tablaMatricula.getColumnModel().getColumn(5).setResizable(false);
        tablaMatricula.getColumnModel().getColumn(6).setResizable(false);
    }
    javax.swing.table.JTableHeader header = tablaMatricula.getTableHeader();
    header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    header.setBackground(new java.awt.Color(245, 245, 245)); // Gris muy claro
    header.setOpaque(true);
    header.setReorderingAllowed(false);
    tablaMatricula.setGridColor(new java.awt.Color(230, 230, 230));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    panelCentral.add(jScrollPane1, gridBagConstraints);
    jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
    jScrollPane1.setBackground(java.awt.Color.WHITE);
    jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());

    panelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

    javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
    panelInferior.setLayout(panelInferiorLayout);
    panelInferiorLayout.setHorizontalGroup(
        panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );
    panelInferiorLayout.setVerticalGroup(
        panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );

    panelPrincipal.add(panelInferior, java.awt.BorderLayout.SOUTH);

    add(panelPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        ejecutarFiltroBusqueda();
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnNuevaMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaMatriculaActionPerformed
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof java.awt.Frame frame && matriculaController != null) {
            DialogNuevaMatricula dialog = new DialogNuevaMatricula(frame, true, matriculaController, this, null);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_btnNuevaMatriculaActionPerformed

    private void btnAnularMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularMatriculaActionPerformed
       if (matriculaController == null) return;
        
        int filaSeleccionada = tablaMatricula.getSelectedRow();
        if (filaSeleccionada < 0) {
            mostrarMensaje("Por favor, seleccione una matrícula de la tabla para anular.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        Matricula matriculaSeleccionada = getMatriculaPorFila(filaSeleccionada);
        if (matriculaSeleccionada == null) return;

        if (!matriculaSeleccionada.getActivo()) {
            mostrarMensaje("Esta matrícula ya se encuentra anulada.", "Aviso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int confirmar = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "¿Está seguro de que desea anular la matrícula " + matriculaSeleccionada.getCodigoMatricula() + "?", 
            "Confirmar Anulación",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            if (matriculaController.anularMatricula(matriculaSeleccionada)) {
                mostrarMensaje("Matrícula anulada con éxito.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                refrescarTabla(matriculaController.obtenerMatriculas());
            } else {
                mostrarMensaje("No se pudo anular la matrícula.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAnularMatriculaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ejecutarFiltroBusqueda();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMatriculaMouseClicked
        if (evt.getClickCount() == 2) { 
        int filaSeleccionada = tablaMatricula.getSelectedRow();
        
        if (filaSeleccionada >= 0 && matriculasCargadas != null) {
            String codigoMatriculaFila = (String) tablaMatricula.getValueAt(filaSeleccionada, 0);
            Matricula matriculaSeleccionada = null;
            
  
            for (int i = 0; i < matriculasCargadas.size(); i++) {
                Matricula mat = matriculasCargadas.get(i);
                
                if (mat.getCodigoMatricula().equals(codigoMatriculaFila)) {
                    matriculaSeleccionada = mat;
                    break; 
                }
            }
            
            if (matriculaSeleccionada != null) {
                abrirDetalle(matriculaSeleccionada);
            }
        }
    }
    }//GEN-LAST:event_tablaMatriculaMouseClicked

    private void txtBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusGained
        if (txtBuscar.getText().equals("Buscar por DNI, Codigo o Nombre del Alumno")) {
            txtBuscar.setText("");
        }
    }//GEN-LAST:event_txtBuscarFocusGained

    private void txtBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusLost
        if (txtBuscar.getText().trim().isEmpty()) {
            txtBuscar.setText("Buscar por DNI, Codigo o Nombre del Alumno");
        }
    }//GEN-LAST:event_txtBuscarFocusLost

    private void ejecutarFiltroBusqueda() {
        if (matriculaController != null) {
            String criterio = txtBuscar.getText().trim();
            List<Matricula> resultados = matriculaController.buscarMatriculas(criterio);
            if (resultados.isEmpty() && !criterio.isEmpty() && !criterio.equals("Buscar por DNI, Codigo o Nombre del Alumno")) {
                mostrarMensaje("No se encontraron registros.", "Búsqueda", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            refrescarTabla(resultados);
        }
    }

    public Matricula getMatriculaPorFila(int fila) {
        if (fila >= 0 && fila < this.matriculasCargadas.size()) {
            return this.matriculasCargadas.get(fila);
        }
        return null;
    }

    public void mostrarMensaje(String mensaje, String titulo, int tipoMensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, titulo, tipoMensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnularMatricula;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNuevaMatricula;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombrePanel;
    private javax.swing.JPanel panelAgregar;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTable tablaMatricula;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
