/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import alumnos.controller.AlumnoController;
import docentes.controller.DocenteController;
import matricula.controller.MatriculaController;
import notas.controller.RegistroBimestralController;
import plan_estudios.controller.PlanEstudiosController;
import shared.IDataListener;

/**
 *
 * @author Alexis
 */
public class VentanaPrincipal extends javax.swing.JFrame  implements IDataListener{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private final AlumnoController alumnoController;
    private final DocenteController docenteController;
    private final MatriculaController matriculaController;
    private final PlanEstudiosController planEstudiosController;
    private final RegistroBimestralController notasController;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        this.alumnoController = new AlumnoController();
        this.docenteController = new DocenteController();
        this.matriculaController = new MatriculaController();
        this.planEstudiosController = new PlanEstudiosController();
        this.notasController = new RegistroBimestralController();
        initComponents();

        this.setLocationRelativeTo(null);
    }
    
    
    @Override
    public void onDataChanged() {
        if (panelAlumnos1 != null) panelAlumnos1.recargarDatos();
        if (panelDocentes1 != null) panelDocentes1.recargarDatos();
        if (panelPlanEstudios1 != null) panelPlanEstudios1.recargarDatos();
        System.out.println("Los datos cambiaron, paneles actualizados.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelNombre = new javax.swing.JPanel();
        lblNombrePanel = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        btnAlumnos = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        btnDocentes = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        btnMatricula = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        btnPlanEstudios = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        btnNotas = new javax.swing.JButton();
        panelContenido = new javax.swing.JPanel();
        panelAlumnos1 = new alumnos.view.PanelAlumnos(alumnoController);
        panelDocentes1 = new docentes.view.PanelDocentes(docenteController);
        panelMatricula1 = new matricula.view.PanelMatricula(matriculaController);
        panelPlanEstudios1 = new plan_estudios.view.PanelPlanEstudios(planEstudiosController);
        panelNotas1 = new notas.view.PanelNotas(notasController);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSidebar.setBackground(new java.awt.Color(102, 255, 102));
        panelSidebar.setLayout(new java.awt.BorderLayout());

        panelSuperior.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelSuperior.setOpaque(false);
        panelSuperior.setLayout(new java.awt.BorderLayout());

        panelNombre.setOpaque(false);
        panelNombre.setLayout(new java.awt.BorderLayout());

        lblNombrePanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombrePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombrePanel.setText("SISTEMA DE GESTIÓN");
        panelNombre.add(lblNombrePanel, java.awt.BorderLayout.CENTER);

        panelSuperior.add(panelNombre, java.awt.BorderLayout.NORTH);

        panelBotones.setOpaque(false);
        panelBotones.setLayout(new javax.swing.BoxLayout(panelBotones, javax.swing.BoxLayout.Y_AXIS));
        panelBotones.add(filler1);

        btnAlumnos.setText("Alumnos");
        btnAlumnos.setBorderPainted(false);
        btnAlumnos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlumnos.setMaximumSize(new java.awt.Dimension(200, 45));
        btnAlumnos.setMinimumSize(new java.awt.Dimension(200, 45));
        btnAlumnos.setPreferredSize(new java.awt.Dimension(200, 45));
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });
        panelBotones.add(btnAlumnos);
        btnAlumnos.getAccessibleContext().setAccessibleName("ALUMNOS");

        panelBotones.add(filler2);

        btnDocentes.setText("Docentes");
        btnDocentes.setBorderPainted(false);
        btnDocentes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDocentes.setMaximumSize(new java.awt.Dimension(200, 45));
        btnDocentes.setMinimumSize(new java.awt.Dimension(200, 45));
        btnDocentes.setPreferredSize(new java.awt.Dimension(200, 45));
        btnDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocentesActionPerformed(evt);
            }
        });
        panelBotones.add(btnDocentes);
        btnDocentes.getAccessibleContext().setAccessibleName("DOCENTES");

        panelBotones.add(filler3);

        btnMatricula.setText("Matrícula");
        btnMatricula.setBorderPainted(false);
        btnMatricula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMatricula.setMaximumSize(new java.awt.Dimension(200, 45));
        btnMatricula.setMinimumSize(new java.awt.Dimension(200, 45));
        btnMatricula.setPreferredSize(new java.awt.Dimension(200, 45));
        btnMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatriculaActionPerformed(evt);
            }
        });
        panelBotones.add(btnMatricula);
        btnMatricula.getAccessibleContext().setAccessibleName("MATRICULA");

        panelBotones.add(filler4);

        btnPlanEstudios.setText("Plan de Estudios");
        btnPlanEstudios.setBorderPainted(false);
        btnPlanEstudios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlanEstudios.setMaximumSize(new java.awt.Dimension(200, 45));
        btnPlanEstudios.setMinimumSize(new java.awt.Dimension(200, 45));
        btnPlanEstudios.setPreferredSize(new java.awt.Dimension(200, 45));
        btnPlanEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanEstudiosActionPerformed(evt);
            }
        });
        panelBotones.add(btnPlanEstudios);
        btnPlanEstudios.getAccessibleContext().setAccessibleName("PLANESTUDIOS");

        panelBotones.add(filler5);

        btnNotas.setText("Notas");
        btnNotas.setBorderPainted(false);
        btnNotas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNotas.setMaximumSize(new java.awt.Dimension(200, 45));
        btnNotas.setMinimumSize(new java.awt.Dimension(200, 45));
        btnNotas.setPreferredSize(new java.awt.Dimension(200, 45));
        btnNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasActionPerformed(evt);
            }
        });
        panelBotones.add(btnNotas);
        btnNotas.getAccessibleContext().setAccessibleName("NOTAS");

        panelSuperior.add(panelBotones, java.awt.BorderLayout.CENTER);

        panelSidebar.add(panelSuperior, java.awt.BorderLayout.NORTH);

        getContentPane().add(panelSidebar, java.awt.BorderLayout.WEST);

        panelContenido.setMinimumSize(new java.awt.Dimension(700, 600));
        panelContenido.setPreferredSize(new java.awt.Dimension(700, 600));
        panelContenido.setLayout(new java.awt.CardLayout());
        panelContenido.add(panelAlumnos1, "ALUMNOS");
        panelContenido.add(panelDocentes1, "DOCENTES");
        panelContenido.add(panelMatricula1, "MATRICULAS");
        panelContenido.add(panelPlanEstudios1, "PLANESTUDIOS");
        panelContenido.add(panelNotas1, "NOTAS");

        getContentPane().add(panelContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(panelContenido.getLayout());
        cl.show(panelContenido, "ALUMNOS");
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void btnDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocentesActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(panelContenido.getLayout());
        cl.show(panelContenido, "DOCENTES");
    }//GEN-LAST:event_btnDocentesActionPerformed

    private void btnMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatriculaActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(panelContenido.getLayout());
        cl.show(panelContenido, "MATRICULAS");
    }//GEN-LAST:event_btnMatriculaActionPerformed

    private void btnPlanEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanEstudiosActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(panelContenido.getLayout());
        cl.show(panelContenido, "PLANESTUDIOS");
    }//GEN-LAST:event_btnPlanEstudiosActionPerformed

    private void btnNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(panelContenido.getLayout());
        cl.show(panelContenido, "NOTAS");
    }//GEN-LAST:event_btnNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "No se pudo aplicar el tema nativo del sistema", ex);
        }

        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnDocentes;
    private javax.swing.JButton btnMatricula;
    private javax.swing.JButton btnNotas;
    private javax.swing.JButton btnPlanEstudios;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel lblNombrePanel;
    private alumnos.view.PanelAlumnos panelAlumnos1;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelContenido;
    private docentes.view.PanelDocentes panelDocentes1;
    private matricula.view.PanelMatricula panelMatricula1;
    private javax.swing.JPanel panelNombre;
    private notas.view.PanelNotas panelNotas1;
    private plan_estudios.view.PanelPlanEstudios panelPlanEstudios1;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables

    
}
