package alumnos.view;
import main.VentanaPrincipal;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

import alumnos.controller.AlumnoController;
import alumnos.model.Alumno;
import alumnos.model.Apoderado;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;

/**
 *
 * @author Alexis
 */
public class DialogNuevoAlumno extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogNuevoAlumno.class.getName());
    private final AlumnoController alumnoController;
    private final PanelAlumnos panelPadre;
    private final Alumno alumnoEdicion;
    /**
     * Creates new form DialogNuevoAlumno
     * @param parent
     * @param modal
     * @param alumnoController
     * @param panelPadre
     * @param alumnoEdicion
     */
    public DialogNuevoAlumno(java.awt.Frame parent, boolean modal, AlumnoController alumnoController, PanelAlumnos panelPadre, Alumno alumnoEdicion) {
        super(parent, modal);
        this.alumnoController = alumnoController;
        this.panelPadre = panelPadre;
        this.alumnoEdicion = alumnoEdicion;
        
        initComponents(); 
        this.setLocationRelativeTo(parent);
        
        if (this.alumnoEdicion != null) {
            cargarDatosEnFormulario();
        }
    }
    
    
    private void cargarDatosEnFormulario() {
        nombrePanel.setText("Modificar Información de Alumno");
        txtDniAlumno.setText(alumnoEdicion.getDni());
        txtDniAlumno.setEditable(false); 
        txtNombresAlumno.setText(alumnoEdicion.getNombres());
        txtApellidosAlumno.setText(alumnoEdicion.getApellidos());
        
        if (alumnoEdicion.getFechaNacimiento() != null) {
            spinFechaNacimiento.setValue(Date.from(alumnoEdicion.getFechaNacimiento().atStartOfDay(ZoneId.systemDefault()).toInstant()));
        }
        
        if (alumnoEdicion.getApoderado() != null) {
            Apoderado ap = alumnoEdicion.getApoderado();
            txtDniApoderado.setText(ap.getDni());
            txtNombresApoderado.setText(ap.getNombres());
            txtApellidosApoderado.setText(ap.getApellidos());
            txtParentesco.setText(ap.getParentesco());
            txtTelefonoApoderado.setText(ap.getTelefono());
            txtCorreoApoderado.setText(ap.getCorreo());
            if (ap.getFechaNacimiento() != null) {
                spinFechaNacimiento1.setValue(Date.from(ap.getFechaNacimiento().atStartOfDay(ZoneId.systemDefault()).toInstant()));
            }
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        nombrePanel = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        panelDatosAlumno = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        panelRowDni = new javax.swing.JPanel();
        lblDniAlumno = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtDniAlumno = new javax.swing.JTextField();
        panelRowNombres = new javax.swing.JPanel();
        lblNombresAlumno = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtNombresAlumno = new javax.swing.JTextField();
        panelRowApellidos = new javax.swing.JPanel();
        lblApellidosAlumno = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtApellidosAlumno = new javax.swing.JTextField();
        panelRowFechaNacimiento = new javax.swing.JPanel();
        lblFechaNacimientoAlumno = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        spinFechaNacimiento = new javax.swing.JSpinner();
        panelDatosApoderado = new javax.swing.JPanel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        panelRowDni1 = new javax.swing.JPanel();
        lblDniApoderado = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtDniApoderado = new javax.swing.JTextField();
        panelRowNombres1 = new javax.swing.JPanel();
        lblNombresApoderado = new javax.swing.JLabel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtNombresApoderado = new javax.swing.JTextField();
        panelRowApellidos1 = new javax.swing.JPanel();
        lblApellidosApoderado = new javax.swing.JLabel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtApellidosApoderado = new javax.swing.JTextField();
        panelRowFechaNacimiento1 = new javax.swing.JPanel();
        lblFechaNacimientoApoderado = new javax.swing.JLabel();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        spinFechaNacimiento1 = new javax.swing.JSpinner();
        panelRowParentesco = new javax.swing.JPanel();
        lblParentesco = new javax.swing.JLabel();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtParentesco = new javax.swing.JTextField();
        panelRowTelefono = new javax.swing.JPanel();
        lblTelefonoApoderado = new javax.swing.JLabel();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtTelefonoApoderado = new javax.swing.JTextField();
        panelRowCorreo = new javax.swing.JPanel();
        lblCorreoApoderado = new javax.swing.JLabel();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        txtCorreoApoderado = new javax.swing.JTextField();
        panelInferior = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 750));
        setModal(true);
        setResizable(false);

        panelPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setLayout(new javax.swing.BoxLayout(panelSuperior, javax.swing.BoxLayout.X_AXIS));

        nombrePanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombrePanel.setText("Información Personal");
        nombrePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        nombrePanel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        nombrePanel.setMaximumSize(new java.awt.Dimension(250, 30));
        nombrePanel.setMinimumSize(new java.awt.Dimension(250, 30));
        nombrePanel.setPreferredSize(new java.awt.Dimension(250, 30));
        panelSuperior.add(nombrePanel);

        panelPrincipal.add(panelSuperior, java.awt.BorderLayout.NORTH);

        panelCentral.setLayout(new java.awt.BorderLayout());

        panelDatosAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Alumno\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        panelDatosAlumno.setLayout(new java.awt.GridBagLayout());
        panelDatosAlumno.add(filler1, new java.awt.GridBagConstraints());

        panelRowDni.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowDni.setMaximumSize(new java.awt.Dimension(32767, 45));
        panelRowDni.setOpaque(false);
        panelRowDni.setLayout(new javax.swing.BoxLayout(panelRowDni, javax.swing.BoxLayout.X_AXIS));

        lblDniAlumno.setText("DNI");
        lblDniAlumno.setMaximumSize(new java.awt.Dimension(120, 30));
        lblDniAlumno.setMinimumSize(new java.awt.Dimension(120, 30));
        lblDniAlumno.setPreferredSize(new java.awt.Dimension(120, 30));
        panelRowDni.add(lblDniAlumno);
        panelRowDni.add(filler3);

        txtDniAlumno.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtDniAlumno.setMinimumSize(new java.awt.Dimension(250, 35));
        txtDniAlumno.setPreferredSize(new java.awt.Dimension(250, 35));
        txtDniAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniAlumnoActionPerformed(evt);
            }
        });
        panelRowDni.add(txtDniAlumno);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosAlumno.add(panelRowDni, gridBagConstraints);

        panelRowNombres.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowNombres.setOpaque(false);
        panelRowNombres.setLayout(new javax.swing.BoxLayout(panelRowNombres, javax.swing.BoxLayout.X_AXIS));

        lblNombresAlumno.setText("Nombres");
        lblNombresAlumno.setMaximumSize(new java.awt.Dimension(120, 30));
        lblNombresAlumno.setMinimumSize(new java.awt.Dimension(120, 30));
        lblNombresAlumno.setPreferredSize(new java.awt.Dimension(120, 30));
        panelRowNombres.add(lblNombresAlumno);
        panelRowNombres.add(filler4);

        txtNombresAlumno.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtNombresAlumno.setMinimumSize(new java.awt.Dimension(250, 35));
        txtNombresAlumno.setPreferredSize(new java.awt.Dimension(250, 35));
        panelRowNombres.add(txtNombresAlumno);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosAlumno.add(panelRowNombres, gridBagConstraints);

        panelRowApellidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowApellidos.setOpaque(false);
        panelRowApellidos.setLayout(new javax.swing.BoxLayout(panelRowApellidos, javax.swing.BoxLayout.X_AXIS));

        lblApellidosAlumno.setText("Apellidos");
        lblApellidosAlumno.setMaximumSize(new java.awt.Dimension(120, 30));
        lblApellidosAlumno.setMinimumSize(new java.awt.Dimension(120, 30));
        lblApellidosAlumno.setPreferredSize(new java.awt.Dimension(120, 30));
        panelRowApellidos.add(lblApellidosAlumno);
        panelRowApellidos.add(filler5);

        txtApellidosAlumno.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtApellidosAlumno.setMinimumSize(new java.awt.Dimension(250, 35));
        txtApellidosAlumno.setPreferredSize(new java.awt.Dimension(250, 35));
        panelRowApellidos.add(txtApellidosAlumno);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosAlumno.add(panelRowApellidos, gridBagConstraints);

        panelRowFechaNacimiento.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowFechaNacimiento.setOpaque(false);
        panelRowFechaNacimiento.setLayout(new javax.swing.BoxLayout(panelRowFechaNacimiento, javax.swing.BoxLayout.X_AXIS));

        lblFechaNacimientoAlumno.setText("Fecha de Nacimiento");
        lblFechaNacimientoAlumno.setMaximumSize(new java.awt.Dimension(120, 30));
        lblFechaNacimientoAlumno.setMinimumSize(new java.awt.Dimension(120, 30));
        lblFechaNacimientoAlumno.setPreferredSize(new java.awt.Dimension(120, 30));
        panelRowFechaNacimiento.add(lblFechaNacimientoAlumno);
        panelRowFechaNacimiento.add(filler6);

        spinFechaNacimiento.setModel(new javax.swing.SpinnerDateModel());
        spinFechaNacimiento.setEditor(new javax.swing.JSpinner.DateEditor(spinFechaNacimiento, "dd/MM/yyyy"));
        panelRowFechaNacimiento.add(spinFechaNacimiento);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosAlumno.add(panelRowFechaNacimiento, gridBagConstraints);

        panelCentral.add(panelDatosAlumno, java.awt.BorderLayout.NORTH);

        panelDatosApoderado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Apoderado\n\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        panelDatosApoderado.setLayout(new java.awt.GridBagLayout());
        panelDatosApoderado.add(filler8, new java.awt.GridBagConstraints());

        panelRowDni1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowDni1.setMaximumSize(new java.awt.Dimension(32767, 45));
        panelRowDni1.setOpaque(false);
        panelRowDni1.setLayout(new javax.swing.BoxLayout(panelRowDni1, javax.swing.BoxLayout.X_AXIS));

        lblDniApoderado.setText("DNI");
        lblDniApoderado.setMaximumSize(new java.awt.Dimension(120, 30));
        lblDniApoderado.setMinimumSize(new java.awt.Dimension(120, 30));
        lblDniApoderado.setPreferredSize(new java.awt.Dimension(120, 30));
        panelRowDni1.add(lblDniApoderado);
        panelRowDni1.add(filler9);

        txtDniApoderado.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtDniApoderado.setMinimumSize(new java.awt.Dimension(250, 35));
        txtDniApoderado.setPreferredSize(new java.awt.Dimension(250, 35));
        txtDniApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniApoderadoActionPerformed(evt);
            }
        });
        panelRowDni1.add(txtDniApoderado);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosApoderado.add(panelRowDni1, gridBagConstraints);

        panelRowNombres1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowNombres1.setOpaque(false);
        panelRowNombres1.setLayout(new javax.swing.BoxLayout(panelRowNombres1, javax.swing.BoxLayout.X_AXIS));

        lblNombresApoderado.setText("Nombres");
        lblNombresApoderado.setMaximumSize(new java.awt.Dimension(120, 30));
        lblNombresApoderado.setMinimumSize(new java.awt.Dimension(120, 30));
        lblNombresApoderado.setPreferredSize(new java.awt.Dimension(120, 30));
        panelRowNombres1.add(lblNombresApoderado);
        panelRowNombres1.add(filler10);

        txtNombresApoderado.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtNombresApoderado.setMinimumSize(new java.awt.Dimension(250, 35));
        txtNombresApoderado.setPreferredSize(new java.awt.Dimension(250, 35));
        txtNombresApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresApoderadoActionPerformed(evt);
            }
        });
        panelRowNombres1.add(txtNombresApoderado);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosApoderado.add(panelRowNombres1, gridBagConstraints);

        panelRowApellidos1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowApellidos1.setOpaque(false);
        panelRowApellidos1.setLayout(new javax.swing.BoxLayout(panelRowApellidos1, javax.swing.BoxLayout.X_AXIS));

        lblApellidosApoderado.setText("Apellidos");
        lblApellidosApoderado.setMaximumSize(new java.awt.Dimension(120, 30));
        lblApellidosApoderado.setMinimumSize(new java.awt.Dimension(120, 30));
        lblApellidosApoderado.setPreferredSize(new java.awt.Dimension(120, 30));
        panelRowApellidos1.add(lblApellidosApoderado);
        panelRowApellidos1.add(filler11);

        txtApellidosApoderado.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtApellidosApoderado.setMinimumSize(new java.awt.Dimension(250, 35));
        txtApellidosApoderado.setPreferredSize(new java.awt.Dimension(250, 35));
        panelRowApellidos1.add(txtApellidosApoderado);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosApoderado.add(panelRowApellidos1, gridBagConstraints);

        panelRowFechaNacimiento1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowFechaNacimiento1.setOpaque(false);
        panelRowFechaNacimiento1.setLayout(new javax.swing.BoxLayout(panelRowFechaNacimiento1, javax.swing.BoxLayout.X_AXIS));

        lblFechaNacimientoApoderado.setText("Fecha de Nacimiento");
        lblFechaNacimientoApoderado.setMaximumSize(new java.awt.Dimension(120, 30));
        lblFechaNacimientoApoderado.setMinimumSize(new java.awt.Dimension(120, 30));
        lblFechaNacimientoApoderado.setPreferredSize(new java.awt.Dimension(120, 30));
        panelRowFechaNacimiento1.add(lblFechaNacimientoApoderado);
        panelRowFechaNacimiento1.add(filler15);

        spinFechaNacimiento1.setModel(new javax.swing.SpinnerDateModel());
        spinFechaNacimiento1.setEditor(new javax.swing.JSpinner.DateEditor(spinFechaNacimiento1, "dd/MM/yyyy"));
        panelRowFechaNacimiento1.add(spinFechaNacimiento1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosApoderado.add(panelRowFechaNacimiento1, gridBagConstraints);

        panelRowParentesco.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowParentesco.setOpaque(false);
        panelRowParentesco.setLayout(new javax.swing.BoxLayout(panelRowParentesco, javax.swing.BoxLayout.X_AXIS));

        lblParentesco.setText("Parentesco");
        lblParentesco.setMaximumSize(new java.awt.Dimension(120, 30));
        lblParentesco.setMinimumSize(new java.awt.Dimension(120, 30));
        lblParentesco.setPreferredSize(new java.awt.Dimension(120, 30));
        panelRowParentesco.add(lblParentesco);
        panelRowParentesco.add(filler12);

        txtParentesco.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtParentesco.setMinimumSize(new java.awt.Dimension(250, 35));
        txtParentesco.setPreferredSize(new java.awt.Dimension(250, 35));
        panelRowParentesco.add(txtParentesco);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosApoderado.add(panelRowParentesco, gridBagConstraints);

        panelRowTelefono.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowTelefono.setOpaque(false);
        panelRowTelefono.setLayout(new javax.swing.BoxLayout(panelRowTelefono, javax.swing.BoxLayout.X_AXIS));

        lblTelefonoApoderado.setText("Teléfono");
        lblTelefonoApoderado.setMaximumSize(new java.awt.Dimension(120, 30));
        lblTelefonoApoderado.setMinimumSize(new java.awt.Dimension(120, 30));
        lblTelefonoApoderado.setPreferredSize(new java.awt.Dimension(120, 30));
        panelRowTelefono.add(lblTelefonoApoderado);
        panelRowTelefono.add(filler13);

        txtTelefonoApoderado.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtTelefonoApoderado.setMinimumSize(new java.awt.Dimension(250, 35));
        txtTelefonoApoderado.setPreferredSize(new java.awt.Dimension(250, 35));
        panelRowTelefono.add(txtTelefonoApoderado);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosApoderado.add(panelRowTelefono, gridBagConstraints);

        panelRowCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelRowCorreo.setOpaque(false);
        panelRowCorreo.setLayout(new javax.swing.BoxLayout(panelRowCorreo, javax.swing.BoxLayout.X_AXIS));

        lblCorreoApoderado.setText("Correo");
        lblCorreoApoderado.setMaximumSize(new java.awt.Dimension(120, 30));
        lblCorreoApoderado.setMinimumSize(new java.awt.Dimension(120, 30));
        lblCorreoApoderado.setPreferredSize(new java.awt.Dimension(120, 30));
        panelRowCorreo.add(lblCorreoApoderado);
        panelRowCorreo.add(filler14);

        txtCorreoApoderado.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtCorreoApoderado.setMinimumSize(new java.awt.Dimension(250, 35));
        txtCorreoApoderado.setPreferredSize(new java.awt.Dimension(250, 35));
        panelRowCorreo.add(txtCorreoApoderado);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosApoderado.add(panelRowCorreo, gridBagConstraints);

        panelCentral.add(panelDatosApoderado, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

        panelInferior.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        panelInferior.setLayout(new javax.swing.BoxLayout(panelInferior, javax.swing.BoxLayout.X_AXIS));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(100, 35));
        btnCancelar.setMinimumSize(new java.awt.Dimension(100, 35));
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 35));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelInferior.add(btnCancelar);
        panelInferior.add(filler7);

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(100, 35));
        btnGuardar.setMinimumSize(new java.awt.Dimension(100, 35));
        btnGuardar.setPreferredSize(new java.awt.Dimension(100, 35));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelInferior.add(btnGuardar);

        panelPrincipal.add(panelInferior, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDniAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniAlumnoActionPerformed

    private void txtDniApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniApoderadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniApoderadoActionPerformed

    private void txtNombresApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresApoderadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresApoderadoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            final boolean exito = (alumnoEdicion != null) 
                ? alumnoController.modificarAlumnoYApoderado(actualizarAlumnoDesdeFormulario())
                : alumnoController.registrarAlumnoYApoderado(obtenerAlumnoDesdeFormulario());

            if (exito) {
                if (panelPadre != null) panelPadre.refrescarTabla(alumnoController.obtenerAlumnos());
                this.dispose();
            } else {
                mostrarMensajeValidacion("Hubo un error de persistencia. Revise la conexión.");
            }
        } catch (IllegalArgumentException | IllegalStateException e) {
            mostrarMensajeValidacion(e.getMessage());
        } catch (RuntimeException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error crítico de sistema al guardar", e);
            mostrarMensajeValidacion("Ocurrió un error inesperado de sistema. Consulte con soporte.");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    private Alumno obtenerAlumnoDesdeFormulario() {
        LocalDate nacAlum = ((Date) spinFechaNacimiento.getValue()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate nacApod = ((Date) spinFechaNacimiento1.getValue()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        Apoderado apod = new Apoderado(txtParentesco.getText().trim(), txtTelefonoApoderado.getText().trim(), txtCorreoApoderado.getText().trim(), 
                                       null, txtDniApoderado.getText().trim(), txtNombresApoderado.getText().trim(), txtApellidosApoderado.getText().trim(), nacApod, true);

        Alumno alum = new Alumno("TEMP", apod, null, txtDniAlumno.getText().trim(), txtNombresAlumno.getText().trim(), txtApellidosAlumno.getText().trim(), nacAlum, true);
        return alum;
    }

    private Alumno actualizarAlumnoDesdeFormulario() {
        Alumno alumMod = new Alumno();
        alumMod.setId(alumnoEdicion.getId());
        alumMod.setCodigoEstudiante(alumnoEdicion.getCodigoEstudiante());
        alumMod.setDni(txtDniAlumno.getText().trim());
        alumMod.setNombres(txtNombresAlumno.getText().trim());
        alumMod.setApellidos(txtApellidosAlumno.getText().trim());
        alumMod.setFechaNacimiento(((Date) spinFechaNacimiento.getValue()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        alumMod.setActivo(alumnoEdicion.isActivo()); 

        Apoderado apMod = new Apoderado();
        apMod.setId(alumnoEdicion.getApoderado().getId());
        apMod.setDni(txtDniApoderado.getText().trim());
        apMod.setNombres(txtNombresApoderado.getText().trim());
        apMod.setApellidos(txtApellidosApoderado.getText().trim());
        apMod.setParentesco(txtParentesco.getText().trim());
        apMod.actualizarContacto(txtTelefonoApoderado.getText().trim(), txtCorreoApoderado.getText().trim());
        apMod.setFechaNacimiento(((Date) spinFechaNacimiento1.getValue()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        apMod.setActivo(alumnoEdicion.getApoderado().isActivo()); 

        alumMod.setApoderado(apMod);
        return alumMod;
    }
    
    public void mostrarMensajeValidacion(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "No se pudo aplicar el tema nativo del sistema", ex);
        }

        
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel lblApellidosAlumno;
    private javax.swing.JLabel lblApellidosApoderado;
    private javax.swing.JLabel lblCorreoApoderado;
    private javax.swing.JLabel lblDniAlumno;
    private javax.swing.JLabel lblDniApoderado;
    private javax.swing.JLabel lblFechaNacimientoAlumno;
    private javax.swing.JLabel lblFechaNacimientoApoderado;
    private javax.swing.JLabel lblNombresAlumno;
    private javax.swing.JLabel lblNombresApoderado;
    private javax.swing.JLabel lblParentesco;
    private javax.swing.JLabel lblTelefonoApoderado;
    private javax.swing.JLabel nombrePanel;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelDatosAlumno;
    private javax.swing.JPanel panelDatosApoderado;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRowApellidos;
    private javax.swing.JPanel panelRowApellidos1;
    private javax.swing.JPanel panelRowCorreo;
    private javax.swing.JPanel panelRowDni;
    private javax.swing.JPanel panelRowDni1;
    private javax.swing.JPanel panelRowFechaNacimiento;
    private javax.swing.JPanel panelRowFechaNacimiento1;
    private javax.swing.JPanel panelRowNombres;
    private javax.swing.JPanel panelRowNombres1;
    private javax.swing.JPanel panelRowParentesco;
    private javax.swing.JPanel panelRowTelefono;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JSpinner spinFechaNacimiento;
    private javax.swing.JSpinner spinFechaNacimiento1;
    private javax.swing.JTextField txtApellidosAlumno;
    private javax.swing.JTextField txtApellidosApoderado;
    private javax.swing.JTextField txtCorreoApoderado;
    private javax.swing.JTextField txtDniAlumno;
    private javax.swing.JTextField txtDniApoderado;
    private javax.swing.JTextField txtNombresAlumno;
    private javax.swing.JTextField txtNombresApoderado;
    private javax.swing.JTextField txtParentesco;
    private javax.swing.JTextField txtTelefonoApoderado;
    // End of variables declaration//GEN-END:variables
}
