package alumnos.view;
import alumnos.controller.AlumnoController;
import alumnos.model.Alumno;
import alumnos.model.Apoderado;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Alexis
 */

public class PanelAlumnos extends javax.swing.JPanel {

    private final AlumnoController alumnoController;
    private List<Alumno> alumnosCargados;
    /**
     * Creates new form PanelAlumnos
     */
    public PanelAlumnos() {
        this.alumnoController = null;
        initComponents();
        this.setBackground(java.awt.Color.WHITE);
    }
    
    public PanelAlumnos(AlumnoController alumnoController) {
        this.alumnoController = alumnoController;
        initComponents();
        if (this.alumnoController != null) {
            javax.swing.SwingUtilities.invokeLater(this::recargarDatos);
        }
    }

    private void recargarDatos() {
        refrescarTabla(alumnoController.obtenerAlumnos());
    }

    public void refrescarTabla(List<Alumno> alumnos) {
        this.alumnosCargados = (alumnos != null) ? alumnos : Collections.emptyList();
        DefaultTableModel modelo = (DefaultTableModel) tablaAlumnos.getModel();
        modelo.setRowCount(0);

        for (Alumno a : this.alumnosCargados) {
            modelo.addRow(new Object[]{
                a.getCodigoEstudiante(),
                a.getDni(),
                a.getNombreCompleto(),
                (a.getApoderado() != null) ? a.getApoderado().getNombreCompleto() : "Sin Apoderado",
                (a.getApoderado() != null) ? a.getApoderado().getParentesco() : "N/A",
                (a.getApoderado() != null) ? a.getApoderado().getTelefono() : "N/A",
                a.isActivo() ? "ACTIVO" : "RETIRADO"
            });
        }
    }


   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelNombre = new javax.swing.JPanel();
        nombrePanel = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 32767));
        panelAgregar = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnBajaAlumno = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnNuevo = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        panelBusqueda = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        cboEstado = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnBuscar = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        panelCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlumnos = new javax.swing.JTable();
        panelInferior = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout());

        panelPrincipal.setOpaque(false);
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setOpaque(false);
        panelSuperior.setLayout(new javax.swing.BoxLayout(panelSuperior, javax.swing.BoxLayout.Y_AXIS));

        panelNombre.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelNombre.setMinimumSize(new java.awt.Dimension(400, 30));
        panelNombre.setOpaque(false);
        panelNombre.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelNombre.setLayout(new java.awt.BorderLayout());

        nombrePanel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nombrePanel.setText("Gestión de Alumnos");
        nombrePanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNombre.add(nombrePanel, java.awt.BorderLayout.WEST);

        panelSuperior.add(panelNombre);
        panelSuperior.add(filler4);

        panelAgregar.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelAgregar.setMinimumSize(new java.awt.Dimension(400, 35));
        panelAgregar.setOpaque(false);
        panelAgregar.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelAgregar.setLayout(new javax.swing.BoxLayout(panelAgregar, javax.swing.BoxLayout.X_AXIS));
        panelAgregar.add(filler6);

        btnBajaAlumno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBajaAlumno.setText("Dar baja Alumno");
        btnBajaAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBajaAlumno.setMaximumSize(new java.awt.Dimension(140, 35));
        btnBajaAlumno.setMinimumSize(new java.awt.Dimension(140, 35));
        btnBajaAlumno.setPreferredSize(new java.awt.Dimension(140, 35));
        btnBajaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaAlumnoActionPerformed(evt);
            }
        });
        panelAgregar.add(btnBajaAlumno);
        panelAgregar.add(filler7);

        btnNuevo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNuevo.setText("Nuevo Alumno");
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setMaximumSize(new java.awt.Dimension(140, 35));
        btnNuevo.setMinimumSize(new java.awt.Dimension(140, 35));
        btnNuevo.setPreferredSize(new java.awt.Dimension(140, 35));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panelAgregar.add(btnNuevo);

        panelSuperior.add(panelAgregar);
        panelSuperior.add(filler3);

        panelBusqueda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelBusqueda.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelBusqueda.setMinimumSize(new java.awt.Dimension(400, 35));
        panelBusqueda.setOpaque(false);
        panelBusqueda.setPreferredSize(new java.awt.Dimension(32767, 35));
        panelBusqueda.setLayout(new javax.swing.BoxLayout(panelBusqueda, javax.swing.BoxLayout.LINE_AXIS));

        txtBuscar.setText("Buscar por Código");
        txtBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        txtBuscar.setMaximumSize(new java.awt.Dimension(32767, 35));
        txtBuscar.setMinimumSize(new java.awt.Dimension(250, 35));
        txtBuscar.setName(""); // NOI18N
        txtBuscar.setPreferredSize(new java.awt.Dimension(250, 35));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        panelBusqueda.add(txtBuscar);
        txtBuscar.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)),
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
    panelBusqueda.add(filler5);

    cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "ACTIVOS", "RETIRADOS" }));
    cboEstado.setMinimumSize(new java.awt.Dimension(72, 35));
    cboEstado.setPreferredSize(new java.awt.Dimension(72, 35));
    cboEstado.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cboEstadoActionPerformed(evt);
        }
    });
    panelBusqueda.add(cboEstado);
    panelBusqueda.add(filler1);

    btnBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    btnBuscar.setText("Buscar");
    btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnBuscar.setMaximumSize(new java.awt.Dimension(140, 35));
    btnBuscar.setMinimumSize(new java.awt.Dimension(140, 35));
    btnBuscar.setPreferredSize(new java.awt.Dimension(140, 35));
    btnBuscar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBuscarActionPerformed(evt);
        }
    });
    panelBusqueda.add(btnBuscar);

    panelSuperior.add(panelBusqueda);
    panelSuperior.add(filler2);

    panelPrincipal.add(panelSuperior, java.awt.BorderLayout.NORTH);

    panelCentral.setLayout(new java.awt.GridBagLayout());

    jScrollPane1.setMinimumSize(new java.awt.Dimension(650, 450));
    jScrollPane1.setPreferredSize(new java.awt.Dimension(650, 450));

    tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null}
        },
        new String [] {
            "Codigo", "DNI", "Nombre Completo", "Nombre Apoderado", "Parentesco con Alumno", "Telefono Apoderado", "Estado del Alumno"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false, false
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    tablaAlumnos.setFillsViewportHeight(true);
    tablaAlumnos.setOpaque(false);
    tablaAlumnos.setRowHeight(40);
    tablaAlumnos.setShowGrid(false);
    tablaAlumnos.setShowHorizontalLines(true);
    tablaAlumnos.getTableHeader().setReorderingAllowed(false);
    tablaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tablaAlumnosMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(tablaAlumnos);
    if (tablaAlumnos.getColumnModel().getColumnCount() > 0) {
        tablaAlumnos.getColumnModel().getColumn(0).setResizable(false);
        tablaAlumnos.getColumnModel().getColumn(1).setResizable(false);
        tablaAlumnos.getColumnModel().getColumn(2).setResizable(false);
        tablaAlumnos.getColumnModel().getColumn(3).setResizable(false);
        tablaAlumnos.getColumnModel().getColumn(4).setResizable(false);
        tablaAlumnos.getColumnModel().getColumn(5).setResizable(false);
        tablaAlumnos.getColumnModel().getColumn(6).setResizable(false);
    }
    javax.swing.table.JTableHeader header = tablaAlumnos.getTableHeader();
    header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    header.setBackground(new java.awt.Color(245, 245, 245)); // Gris muy claro
    header.setOpaque(true);
    header.setReorderingAllowed(false);
    tablaAlumnos.setGridColor(new java.awt.Color(230, 230, 230));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    panelCentral.add(jScrollPane1, gridBagConstraints);
    jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
    jScrollPane1.setBackground(java.awt.Color.WHITE);
    jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());

    panelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

    javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
    panelInferior.setLayout(panelInferiorLayout);
    panelInferiorLayout.setHorizontalGroup(
        panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );
    panelInferiorLayout.setVerticalGroup(
        panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );

    panelPrincipal.add(panelInferior, java.awt.BorderLayout.SOUTH);

    add(panelPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof java.awt.Frame frame) {
            DialogNuevoAlumno dialog = new DialogNuevoAlumno(frame, true, alumnoController, this, null);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        ejecutarBusqueda();
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ejecutarBusqueda();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlumnosMouseClicked
        if (evt.getClickCount() == 2) { 
            int filaSeleccionada = tablaAlumnos.getSelectedRow();

            if (filaSeleccionada >= 0) {
                String codigoFila = (String) tablaAlumnos.getValueAt(filaSeleccionada, 0);

                Alumno alumnoParaEditar = alumnoController.obtenerAlumnoParaEdicion(codigoFila);

                if (alumnoParaEditar != null) {
                    java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
                    if (parentWindow instanceof java.awt.Frame frame) {
                        DialogNuevoAlumno dialog = new DialogNuevoAlumno(frame, true, alumnoController, this, alumnoParaEditar);
                        dialog.setVisible(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_tablaAlumnosMouseClicked

    private void cboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoActionPerformed
        if (alumnoController == null) return;
    
        String seleccion = (String) cboEstado.getSelectedItem();

        List<Alumno> resultadosFiltrados = alumnoController.obtenerAlumnosPorEstado(seleccion);

        refrescarTabla(resultadosFiltrados);
    }//GEN-LAST:event_cboEstadoActionPerformed

    private void btnBajaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaAlumnoActionPerformed
    int filaSeleccionada = tablaAlumnos.getSelectedRow();

    if (filaSeleccionada == -1) {
        mostrarError("Por favor, seleccione un alumno de la tabla.");
        return;
    }

    
    String codigo = (String) tablaAlumnos.getValueAt(filaSeleccionada, 0);
    
    Alumno alumnoParaBaja = alumnosCargados.stream()
            .filter(a -> a.getCodigoEstudiante().equals(codigo))
            .findFirst()
            .orElse(null);

    if (alumnoParaBaja == null) return;

    int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de dar de baja al alumno " + alumnoParaBaja.getNombreCompleto() + "?", 
            "Confirmar Baja", 
            javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
        boolean resultado = alumnoController.procesarBajaAlumno(alumnoParaBaja);

        if (resultado) {
            javax.swing.JOptionPane.showMessageDialog(this, "Alumno dado de baja correctamente.");
            refrescarTabla(alumnoController.obtenerAlumnos());
        } else {
            mostrarError("No se pudo procesar la baja. Intente nuevamente.");
        }
    }
    }//GEN-LAST:event_btnBajaAlumnoActionPerformed

    public void mostrarError(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    
    private void ejecutarBusqueda() {
        String codigoBusqueda = txtBuscar.getText().trim();
        List<Alumno> resultados = alumnoController.buscarPorCodigo(codigoBusqueda);
        
        if (resultados.isEmpty() && !codigoBusqueda.isEmpty() && !codigoBusqueda.equals("Buscar por Código")) {
            refrescarTabla(Collections.emptyList());
            mostrarError("No se encontró ningún estudiante con el código: " + codigoBusqueda);
        } else {
            refrescarTabla(resultados);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBajaAlumno;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombrePanel;
    private javax.swing.JPanel panelAgregar;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTable tablaAlumnos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
