package notas.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import main.VentanaPrincipal;
import notas.model.Evaluacion;
import notas.model.RegistroBimestral;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Alexis
 */
public class DialogDetalleAlumno extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogDetalleAlumno.class.getName());

    /**
     * Creates new form DialogDetalleAlumno
     * @param parent
     * @param modal
     * @param nombreAlumno
     * @param gradoAlumno
     */
    public DialogDetalleAlumno(java.awt.Frame parent, boolean modal, String nombreAlumno, String gradoAlumno, List<RegistroBimestral> historial) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        lblNombreAlumno.setText("Alumno: " + nombreAlumno);
        lblGradoAlumno.setText("Grado: " + gradoAlumno);
        
        cargarHistorialEnTabla(historial);
    }
    
    private void cargarHistorialEnTabla(List<RegistroBimestral> historial) {
        DefaultTableModel modelo = (DefaultTableModel) panelDatosAlumnoRiesgo.getModel();
        modelo.setRowCount(0);
 
        for (RegistroBimestral rb : historial) {
            double practicas = 0, tareas = 0, parcial = 0, bimestral = 0;
            
            for (Evaluacion e : rb.getEvaluaciones()) {
                if (null != e.getTipo()) switch (e.getTipo()) {
                    case PRACTICA:
                        practicas = e.getNota();
                        break;
                    case TAREA:
                        tareas = e.getNota();
                        break;
                    case PARCIAL:
                        parcial = e.getNota();
                        break;
                    case BIMESTRAL:
                        bimestral = e.getNota();
                        break;
                    default:
                        break;
                }
}
 
            modelo.addRow(new Object[]{
                "Bimestre " + rb.getBimestre(),
                rb.getMatriculaCurso() != null && rb.getMatriculaCurso().getCurso() != null ? rb.getMatriculaCurso().getCurso().getNombre() : "S/C",
                practicas,
                tareas,
                parcial,
                bimestral,
                rb.calcularPromedio()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        lblNombrePanel = new javax.swing.JLabel();
        lblNombreAlumno = new javax.swing.JLabel();
        lblGradoAlumno = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelDatosAlumnoRiesgo = new javax.swing.JTable();
        panelInferior = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 600));
        setModal(true);

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        panelSuperior.setLayout(new javax.swing.BoxLayout(panelSuperior, javax.swing.BoxLayout.Y_AXIS));

        lblNombrePanel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombrePanel.setText("Kardex Académico");
        panelSuperior.add(lblNombrePanel);

        lblNombreAlumno.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNombreAlumno.setText("Alumno:  Nombre Alumno");
        panelSuperior.add(lblNombreAlumno);

        lblGradoAlumno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGradoAlumno.setText("Grado:  Grado actual");
        panelSuperior.add(lblGradoAlumno);

        panelPrincipal.add(panelSuperior, java.awt.BorderLayout.NORTH);

        panelCentral.setLayout(new java.awt.BorderLayout());

        panelDatosAlumnoRiesgo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Bimestre", "Curso", "Promedio Prácticas", "Promedio Tareas", "Ex. Parcial", "Ex. Bimestral", "Promedio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(panelDatosAlumnoRiesgo);
        if (panelDatosAlumnoRiesgo.getColumnModel().getColumnCount() > 0) {
            panelDatosAlumnoRiesgo.getColumnModel().getColumn(0).setResizable(false);
            panelDatosAlumnoRiesgo.getColumnModel().getColumn(1).setResizable(false);
            panelDatosAlumnoRiesgo.getColumnModel().getColumn(2).setResizable(false);
            panelDatosAlumnoRiesgo.getColumnModel().getColumn(3).setResizable(false);
            panelDatosAlumnoRiesgo.getColumnModel().getColumn(4).setResizable(false);
            panelDatosAlumnoRiesgo.getColumnModel().getColumn(5).setResizable(false);
        }

        panelCentral.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

        panelInferior.setLayout(new java.awt.BorderLayout());

        panelBotones.setLayout(new javax.swing.BoxLayout(panelBotones, javax.swing.BoxLayout.LINE_AXIS));

        btnCerrar.setText("Cerrar");
        btnCerrar.setMaximumSize(new java.awt.Dimension(75, 35));
        btnCerrar.setMinimumSize(new java.awt.Dimension(75, 35));
        btnCerrar.setPreferredSize(new java.awt.Dimension(75, 35));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        panelBotones.add(btnCerrar);
        panelBotones.add(filler1);

        btnExportar.setText("Exportar PDF");
        btnExportar.setMaximumSize(new java.awt.Dimension(120, 35));
        btnExportar.setMinimumSize(new java.awt.Dimension(120, 35));
        btnExportar.setPreferredSize(new java.awt.Dimension(120, 35));
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        panelBotones.add(btnExportar);

        panelInferior.add(panelBotones, java.awt.BorderLayout.EAST);

        panelPrincipal.add(panelInferior, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "La exportación a PDF aún no está implementada.", "SAD Calificaciones", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnExportarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "No se pudo aplicar el tema nativo del sistema", ex);
        }

        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnExportar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGradoAlumno;
    private javax.swing.JLabel lblNombreAlumno;
    private javax.swing.JLabel lblNombrePanel;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JTable panelDatosAlumnoRiesgo;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables
}
