
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package notas.view;

import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.VentanaPrincipal;
import notas.controller.RegistroBimestralController;
import notas.model.Evaluacion;
import notas.model.RegistroBimestral;

/**
 *
 * @author Alexis
 */
public class DialogDetalleNotas extends javax.swing.JDialog {
    
    private static final Logger logger = Logger.getLogger(DialogDetalleNotas.class.getName());
    private final RegistroBimestralController controller;
    private final Integer idRegistroBimestralActual;
    private List<Evaluacion> evaluacionesActuales;
    private boolean esBimestreActivo = true;
    
    /**
     * Creates new form DialogDetalleAlumno
     * @param parent
     * @param modal
     * @param controller
     * @param idRegistro
     * @param nombreAlumno
     * @param curso
     * @param bimestre
     * @param esActivo
     */
    public DialogDetalleNotas(java.awt.Frame parent, boolean modal, RegistroBimestralController controller,
                          Integer idRegistro, String nombreAlumno, String curso, String bimestre, boolean esActivo) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.controller = controller;
        this.idRegistroBimestralActual = idRegistro;
        this.esBimestreActivo = esActivo;

        lblNombrePanel.setText("Detalle de Evaluaciones");
        lblNombreAlumno.setText("Alumno: " + nombreAlumno);
        lblGradoAlumno.setText("Curso: " + curso + " | " + bimestre);

        cargarEvaluaciones();

        if (!this.esBimestreActivo) {
            btnGuardarNotas.setEnabled(false);
            btnAgregarNota.setEnabled(false);
            btnEliminarNota.setEnabled(false);

            if (jPanel1 != null) {
                jPanel1.setEnabled(false);
            }

            lblNombrePanel.setText("Detalle de Evaluaciones - [BIMESTRE CERRADO]");

            panelDatosAlumnoRiesgo.setDefaultEditor(Object.class, null);
        }
    }
    
    private void cargarEvaluaciones() {
        if (controller == null || idRegistroBimestralActual == null) return;
        
        DefaultTableModel modelo = (DefaultTableModel) panelDatosAlumnoRiesgo.getModel();
        modelo.setRowCount(0);
        
        try {
            evaluacionesActuales = controller.obtenerEvaluacionesPorRegistro(idRegistroBimestralActual);
            for (Evaluacion e : evaluacionesActuales) {
                modelo.addRow(new Object[]{ e.getTipo(), e.getNombre(), e.getNota(), e.getPeso() });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelNombre = new javax.swing.JPanel();
        lblNombrePanel = new javax.swing.JLabel();
        lblNombreAlumno = new javax.swing.JLabel();
        lblGradoAlumno = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEliminarNota = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        btnAgregarNota = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelDatosAlumnoRiesgo = new javax.swing.JTable();
        panelInferior = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        btnGuardarNotas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 600));
        setModal(true);

        panelPrincipal.setOpaque(false);
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        panelSuperior.setLayout(new java.awt.BorderLayout());

        panelNombre.setLayout(new javax.swing.BoxLayout(panelNombre, javax.swing.BoxLayout.Y_AXIS));

        lblNombrePanel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombrePanel.setText("Kardex Académico");
        panelNombre.add(lblNombrePanel);

        lblNombreAlumno.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNombreAlumno.setText("Alumno:  Nombre Alumno");
        panelNombre.add(lblNombreAlumno);

        lblGradoAlumno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGradoAlumno.setText("Grado:  Grado actual");
        panelNombre.add(lblGradoAlumno);

        panelSuperior.add(panelNombre, java.awt.BorderLayout.WEST);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        btnEliminarNota.setText("Eliminar Nota");
        btnEliminarNota.setMaximumSize(new java.awt.Dimension(120, 35));
        btnEliminarNota.setMinimumSize(new java.awt.Dimension(120, 35));
        btnEliminarNota.setPreferredSize(new java.awt.Dimension(120, 35));
        btnEliminarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarNotaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarNota);
        jPanel1.add(filler2);

        btnAgregarNota.setText("Agregar Nota");
        btnAgregarNota.setMaximumSize(new java.awt.Dimension(120, 35));
        btnAgregarNota.setMinimumSize(new java.awt.Dimension(120, 35));
        btnAgregarNota.setPreferredSize(new java.awt.Dimension(120, 35));
        btnAgregarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNotaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarNota);

        panelSuperior.add(jPanel1, java.awt.BorderLayout.EAST);

        panelPrincipal.add(panelSuperior, java.awt.BorderLayout.NORTH);

        panelCentral.setLayout(new java.awt.BorderLayout());

        panelDatosAlumnoRiesgo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipo", "Nombre de evaluación", "Nota", "Peso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelDatosAlumnoRiesgo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(panelDatosAlumnoRiesgo);
        if (panelDatosAlumnoRiesgo.getColumnModel().getColumnCount() > 0) {
            panelDatosAlumnoRiesgo.getColumnModel().getColumn(0).setResizable(false);
            panelDatosAlumnoRiesgo.getColumnModel().getColumn(1).setResizable(false);
            panelDatosAlumnoRiesgo.getColumnModel().getColumn(2).setResizable(false);
            panelDatosAlumnoRiesgo.getColumnModel().getColumn(3).setResizable(false);
        }

        panelCentral.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

        panelInferior.setLayout(new java.awt.BorderLayout());

        panelBotones.setLayout(new javax.swing.BoxLayout(panelBotones, javax.swing.BoxLayout.LINE_AXIS));

        btnCerrar.setText("Cerrar");
        btnCerrar.setMaximumSize(new java.awt.Dimension(75, 35));
        btnCerrar.setMinimumSize(new java.awt.Dimension(75, 35));
        btnCerrar.setPreferredSize(new java.awt.Dimension(75, 35));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        panelBotones.add(btnCerrar);
        panelBotones.add(filler1);

        btnGuardarNotas.setText("Guardar Notas");
        btnGuardarNotas.setMaximumSize(new java.awt.Dimension(120, 35));
        btnGuardarNotas.setMinimumSize(new java.awt.Dimension(120, 35));
        btnGuardarNotas.setPreferredSize(new java.awt.Dimension(120, 35));
        btnGuardarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNotasActionPerformed(evt);
            }
        });
        panelBotones.add(btnGuardarNotas);

        panelInferior.add(panelBotones, java.awt.BorderLayout.EAST);

        panelPrincipal.add(panelInferior, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNotasActionPerformed
    if (panelDatosAlumnoRiesgo.isEditing()) {
        panelDatosAlumnoRiesgo.getCellEditor().stopCellEditing();
    }

    DefaultTableModel modelo = (DefaultTableModel) panelDatosAlumnoRiesgo.getModel();
    List<Evaluacion> cambios = new ArrayList<>();

    try {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            Object valorNota = modelo.getValueAt(i, 2);
            if (valorNota == null || valorNota.toString().trim().isEmpty()) continue;
            
            double nuevaNota = Double.parseDouble(valorNota.toString());
            String nombreEvalTabla = modelo.getValueAt(i, 1).toString();
            
            boolean encontrada = false;
            for (Evaluacion e : evaluacionesActuales) {
                if (e.getNombre().equals(nombreEvalTabla)) {
                    e.setNota(nuevaNota); 
                    cambios.add(e);
                    encontrada = true;
                    break;
                }
            }
            
            if (!encontrada) {
                shared.TipoEvaluacion tipoEval = (shared.TipoEvaluacion) modelo.getValueAt(i, 0);
                Evaluacion nueva = new Evaluacion(null, null, nombreEvalTabla, tipoEval, nuevaNota, tipoEval.getPeso());
                cambios.add(nueva);
            }
        }
        
        controller.guardarEvaluacionesDetalle(idRegistroBimestralActual, cambios);
        
        JOptionPane.showMessageDialog(this, "Notas guardadas correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Por favor ingrese un número válido en la columna Nota.", "Error de Formato", JOptionPane.WARNING_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGuardarNotasActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAgregarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNotaActionPerformed
    shared.TipoEvaluacion[] tipos = shared.TipoEvaluacion.values();
        shared.TipoEvaluacion seleccionado = (shared.TipoEvaluacion) JOptionPane.showInputDialog(this, 
                "Seleccione el tipo de evaluación:", "Nueva Evaluación", 
                JOptionPane.QUESTION_MESSAGE, null, tipos, tipos[0]);

        if (seleccionado != null) {
            try {
                RegistroBimestral validador = new RegistroBimestral();
                validador.setEvaluaciones(evaluacionesActuales); 
                validador.validarNuevaEvaluacion(seleccionado); 
                
                String nombreSugerido = "Nuevo " + seleccionado.name();
                Evaluacion nuevaTemp = new Evaluacion(null, null, nombreSugerido, seleccionado, 0.0, seleccionado.getPeso());
                
                evaluacionesActuales.add(nuevaTemp);
                
                DefaultTableModel modelo = (DefaultTableModel) panelDatosAlumnoRiesgo.getModel();
                modelo.addRow(new Object[]{ nuevaTemp.getTipo(), nuevaTemp.getNombre(), nuevaTemp.getNota(), nuevaTemp.getPeso() });
                
            } catch (IllegalStateException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Límite Alcanzado", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAgregarNotaActionPerformed

    private void btnEliminarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarNotaActionPerformed
        int fila = panelDatosAlumnoRiesgo.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione la evaluación que desea eliminar de la tabla.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar esta evaluación? Esto recalculará el promedio.", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) return;

    try {
        Evaluacion evalAEliminar = evaluacionesActuales.get(fila);

        if (evalAEliminar.getId() != null) {
            controller.eliminarEvaluacion(evalAEliminar.getId(), idRegistroBimestralActual);
        }

        evaluacionesActuales.remove(fila);

        DefaultTableModel modelo = (DefaultTableModel) panelDatosAlumnoRiesgo.getModel();
        modelo.removeRow(fila);

        JOptionPane.showMessageDialog(this, "Evaluación eliminada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al eliminar la nota: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEliminarNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "No se pudo aplicar el tema nativo del sistema", ex);
        }

        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarNota;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminarNota;
    private javax.swing.JButton btnGuardarNotas;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGradoAlumno;
    private javax.swing.JLabel lblNombreAlumno;
    private javax.swing.JLabel lblNombrePanel;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JTable panelDatosAlumnoRiesgo;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables
}
